export const articles = [
  { slug: 'zero-trust-practical-guide', title: 'Zero Trust in 2026: A Practical Enterprise Roadmap', category: 'Cybersecurity', author: 'Attique Bhatti', date: 'Jun 12, 2026', readTime: '12 min', excerpt: 'What Zero Trust actually means in 2026 — and a 6-step roadmap you can start this quarter.', img: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5', body: [
    { h2: 'What Zero Trust actually means' },
    { p: 'Zero Trust is an architecture, not a product. It is a shift from perimeter-based trust to identity-centric, continuously verified access decisions. In 2026, the mature form of Zero Trust combines strong identity (MFA, conditional access, device posture), micro-segmentation (ZTNA, ZTWA), and continuous verification.' },
    { h2: 'The 6-step practical roadmap' },
    { p: 'Start with a CISA Zero Trust Maturity Model (ZTMM) scoring across five pillars: Identity, Device, Network, Application Workload and Data. Pick one pillar and one use-case that drives measurable value in 90 days — typically ZTNA for remote access or Conditional Access for identity. Then scale outward.' },
    { h2: 'Common pitfalls' },
    { p: 'The #1 mistake is treating Zero Trust as a vendor bake-off. Vendors matter, but architecture matters more. The second mistake is scope creep — trying to boil the ocean kills program momentum. Ship a beachhead use-case, measure outcomes, then scale.' },
  ] },
  { slug: 'stadium-wifi-72-hours', title: 'How We Powered a 50,000-Seat Stadium Network in 72 Hours', category: 'Event IT', author: 'Rahul Kapoor', date: 'May 28, 2026', readTime: '9 min', excerpt: 'Inside the planning, kit list and on-site playbook that delivered event WiFi for one of the region’s biggest sporting events.', img: 'https://images.unsplash.com/photo-1548092372-0d1bd40894a3', body: [
    { h2: 'The brief' },
    { p: 'A major sporting event. 72 hours from venue handover to kickoff. 50,000 fans, 2,000 press and production, plus a broadcast LAN. Our team had done this before — but never this fast.' },
    { h2: 'The kit' },
    { p: '220 HPE Aruba AP-635 WiFi 6E access points, 48 Ubiquiti PtP links, 12 core switches, a full temporary NOC in a 12U portable rack, and two 10 Gbps microwave uplinks to the broadcast compound.' },
    { h2: 'What went right' },
    { p: 'Predictive RF modelling (Ekahau). Pre-staged, pre-tested gear. A playbook from 30+ prior events. 18 engineers on site in shifts. Zero P1 incidents during the event.' },
  ] },
  { slug: 'finops-azure-cut-spend', title: 'FinOps for Mid-Market: Cutting Azure Spend by 34%', category: 'Managed IT', author: 'Sarah Chen', date: 'May 15, 2026', readTime: '11 min', excerpt: 'The FinOps playbook we ran with a mid-market SaaS client that delivered 34% Azure savings in 90 days.', img: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b', body: [{ p: 'Most cloud overspend is structural, not behavioural. Fix the structure first — right-sizing, Reserved Instances, and shutdown schedules deliver 70% of the gains with 30% of the effort.' }] },
  { slug: 'sase-vendor-evaluation', title: 'Evaluating SASE Vendors in 2026: A Practical Framework', category: 'Cybersecurity', author: 'Attique Bhatti', date: 'May 08, 2026', readTime: '14 min', excerpt: 'A vendor-neutral framework for choosing between Palo Alto, Zscaler, Netskope and Cisco SASE.', img: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3', body: [{ p: 'Start with integrations and starting point, not feature matrices. Feature parity is closer than anyone admits.' }] },
  { slug: 'wifi-7-real-world', title: 'WiFi 7 in the Real World: What’s Actually Different', category: 'Networking', author: 'Rahul Kapoor', date: 'Apr 28, 2026', readTime: '7 min', excerpt: 'We’ve deployed WiFi 7 in four venues this year. Here’s what’s genuinely different and what isn’t.', img: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f', body: [{ p: 'MLO (Multi-Link Operation) is the real story. The raw throughput numbers are less interesting than the latency behaviour.' }] },
  { slug: 'laptop-rental-vs-buy', title: 'Rent or Buy: The Real Math on Enterprise Laptops', category: 'Rentals', author: 'Sarah Chen', date: 'Apr 20, 2026', readTime: '6 min', excerpt: 'We ran the numbers across 20 client scenarios. When does renting actually beat buying?', img: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853', body: [{ p: 'For temporary projects under 18 months, rental wins consistently. Above 24 months, purchase with a 3-year refresh wins.' }] },
  { slug: 'elv-converged-security', title: 'Converged Security: Why ELV and Cyber Should Be One Team', category: 'Cybersecurity', author: 'Attique Bhatti', date: 'Apr 12, 2026', readTime: '10 min', excerpt: 'Your CCTV network is an IoT estate. Treat it accordingly — or expect to be the next breach story.', img: 'https://images.unsplash.com/photo-1557804506-669a67965ba0', body: [{ p: 'In most enterprises, the CCTV VLAN is the soft underbelly. Attackers know. Security teams rarely do.' }] },
  { slug: 'ipcare-nba-toronto', title: 'Case Study: NBA Global Games in Toronto', category: 'News', author: 'IP Care Team', date: 'Apr 02, 2026', readTime: '8 min', excerpt: 'Behind the scenes at the Scotiabank Arena: the network refresh that powered a global sporting event.', img: 'https://images.unsplash.com/photo-1563841930606-67e2bce48b78', body: [{ p: 'Over 20,000 fans per night. Live broadcast to 150+ countries. Zero network incidents across five days.' }] },
  { slug: 'xsiam-vs-legacy-siem', title: 'XSIAM vs. Legacy SIEM: When the Migration Makes Sense', category: 'Cybersecurity', author: 'Attique Bhatti', date: 'Mar 25, 2026', readTime: '13 min', excerpt: 'We’ve migrated three enterprises from Splunk to XSIAM this year. Here’s the decision framework.', img: 'https://images.unsplash.com/photo-1504384764586-bb4cdc1707b0', body: [{ p: 'The honest answer: it depends. But the dependencies are fewer than you’d think.' }] },
  {
    slug: 'choosing-managed-it-provider-uae',
    title: 'Choosing a Managed IT Provider in the UAE: 7 Questions to Ask',
    category: 'Managed IT',
    author: 'IP Care Team',
    date: 'May 05, 2026',
    readTime: '9 min',
    excerpt: 'Most MSP pitches sound identical. These seven questions surface the differences that actually matter once the contract is signed.',
    img: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d',
    body: [
      { h2: 'Why most MSP comparisons fail' },
      { p: 'Every managed IT provider in the UAE claims 24×7 support, SLA-backed response and certified engineers. On paper, they look the same. The real differences only show up after the contract is signed and the first incident hits.' },
      { p: 'These seven questions are designed to surface those differences before you sign. They are the ones we wish more clients asked us in their first meeting.' },
      { h2: '1. What does your P1 response look like — in numbers, last month?' },
      { p: 'Forget the SLA on paper. Ask for the actual P1 response time average from the previous month, with a sample of ticket IDs. Providers that publish this monthly are operating on a different level than those that quote a target.' },
      { h2: '2. Where do my tickets get answered, and by whom?' },
      { p: 'Offshore tier-one queues are not inherently bad — but you should know. Ask if your first responder will be UAE-based or routed offshore. Ask the experience level of that responder. Cheap MSPs hide this.' },
      { h2: '3. What happens if you miss the SLA?' },
      { p: 'A contract without service credits is a contract without consequences. Real SLAs come with financial credits when missed, written in plain language. If the response is "we never miss," walk away — that is marketing, not operations.' },
      { h2: '4. Show me your last quarterly business review for a similar client.' },
      { p: 'Quarterly reviews separate operators from order-takers. The good MSPs run them as a discipline — anonymised numbers, capacity trends, security posture, planned work. The bad MSPs invent one for the sales meeting and never run another.' },
      { h2: '5. How do you handle scope creep?' },
      { p: 'Every managed contract grows in scope. The question is how the MSP handles it. Transparent change requests with documented impact? Or quiet hours billed retrospectively? Ask for the change request template.' },
      { h2: '6. Who owns the relationship after sales handover?' },
      { p: 'Sales engineers are great. They also disappear after signing. Ask who the named service delivery manager will be, and ask to meet them before the contract. If you cannot get a name, the role does not exist.' },
      { h2: '7. What is your exit process?' },
      { p: 'The contract you can leave is the contract worth signing. Ask how documentation, credentials, monitoring and asset registers transfer back if you part ways. A confident MSP answers this directly. An anxious one redirects to commercial terms.' },
      { h2: 'The signal vs. the noise' },
      { p: 'The right MSP for your business is not the one with the best deck. It is the one whose answers to these questions sound like they have been answered before — because the way they run the operation has already produced them.' },
    ],
  },
  {
    slug: 'nesa-compliance-90-days',
    title: 'NESA Compliance in 90 Days: What Actually Moves the Needle',
    category: 'Cybersecurity',
    author: 'Attique Bhatti',
    date: 'Apr 24, 2026',
    readTime: '11 min',
    excerpt: 'You have an IAS audit in three months and gaps you did not know existed. Here is what to prioritise — and what to defer.',
    img: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3',
    body: [
      { h2: 'The 90-day NESA problem' },
      { p: 'Most NESA conversations start with an audit notice and a calendar that no longer has slack in it. The internal team has 90 days to close gaps that built up over years. The right question is not "how do we comply" — it is "what is the smallest amount of work that gets us to a defensible posture in time."' },
      { h2: 'Phase 1 — Weeks 1 to 2: gap assessment, no theatre' },
      { p: 'Map your current controls to the IAS framework honestly. Score every domain red, amber or green. Resist the temptation to colour-grade yourself green where you are amber. The auditor will not.' },
      { p: 'Output of this phase: a one-page gap heatmap, a prioritised remediation list with effort estimates, and a named owner for each control.' },
      { h2: 'Phase 2 — Weeks 3 to 8: close the structural gaps' },
      { p: 'Three areas almost always need work in a first NESA cycle. They are the ones we recommend tackling first because they take time and cannot be faked: asset and vendor inventories, privileged access controls, and tested business continuity plans.' },
      { p: 'Asset inventory: an actual inventory, not the spreadsheet from 2022. Vendors with access to your environment count. Privileged access: vault the credentials, enable session recording, restrict standing access. Business continuity: a tabletop exercise with the actual incident response team, not a plan in SharePoint that no-one has opened.' },
      { h2: 'Phase 3 — Weeks 9 to 11: control evidence and documentation' },
      { p: 'The auditor will spend most of their time asking for evidence. Pre-build the evidence packs — control narratives, configuration screenshots, log samples, exception registers. Run a mock audit internally before the real one. The mock audit will find at least three things you missed.' },
      { h2: 'Phase 4 — Week 12: rehearsal and audit' },
      { p: 'Final week is rehearsal. The team that will sit in the audit room should know the control narratives without reading from notes. Auditors respect confidence and specificity. They mark down ambiguity.' },
      { h2: 'What to defer' },
      { p: 'Aspirational controls — automation, advanced threat hunting, fully integrated GRC platforms — do not move the needle in a 90-day window. They are the right work for the next cycle, not this one. Defer them.' },
      { p: 'The version of this story where you are not panicking starts twelve months earlier. If that is your timeline, that is a different article. If you have 90 days, focus on the structural three and stop.' },
    ],
  },
  {
    slug: 'nesa-vs-iso-27001',
    title: 'NESA vs ISO 27001: Where They Overlap, Where They Don’t, and Which to Do First',
    category: 'Cybersecurity',
    author: 'Attique Bhatti',
    date: 'May 11, 2026',
    readTime: '13 min',
    excerpt: 'About 70 percent of ISO 27001 controls map straight into NESA. The other 30 percent is where most UAE enterprises lose two months of work they did not need to lose.',
    img: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85',
    body: [
      { h2: 'The question every UAE compliance lead asks twice' },
      { p: 'If you run information security for a UAE enterprise in banking, energy, government, telecom, transport or healthcare, you will eventually be asked the same question by your CFO or your board: do we need both NESA and ISO 27001, or does one cover the other? The honest answer is: they overlap heavily, they are not equivalent, and the smart way to run them is as one programme — not two.' },
      { p: 'This post explains where the two frameworks overlap, where they diverge, and how to sequence them so the second certification costs a fraction of the first. It is written for the compliance lead, security manager or CIO who has been told to deliver one or both and wants to know how to avoid doing the same control implementation twice.' },
      { h2: 'A 30-second framing' },
      { p: 'ISO/IEC 27001 is a globally recognised information security management system (ISMS) standard. It is voluntary in most jurisdictions, certificate-based, and renewed every three years with annual surveillance audits. It is recognised by customers, regulators and partners worldwide as proof that an organisation runs a credible information security programme.' },
      { p: 'NESA — properly the UAE Information Assurance Standards, originally published by the National Electronic Security Authority in 2014 and now under the UAE Cyber Security Council — is a mandatory framework for organisations operating in UAE critical sectors. It is enforced through your sector regulator (UAE Central Bank, TDRA, DOH, ADNOC GRP, FAHR, etc.) and audited against a defined evidence checklist using the Information Assurance Maturity Model.' },
      { p: 'Both frameworks define controls. Both require risk-based prioritisation. Both expect evidence, attestation and continuous improvement. That is where the family resemblance ends.' },
      { h2: 'Where they overlap (about 70 percent)' },
      { p: 'The bulk of operational security controls — access control, cryptography, physical security, operations security, communications security, incident management, business continuity, supplier security — appear in both frameworks in similar shape. ISO 27001 Annex A and the NESA technical control families T1 through T9 are different organisations of largely the same content.' },
      { p: 'In practice, a well-run ISO 27001 ISMS gets you to roughly 70 percent of NESA technical compliance without additional engineering work. The Statement of Applicability you produced for ISO 27001 maps almost line-for-line to the NESA technical control selection. Most of the policies you wrote for ISO — acceptable use, classification, incident response, BCP — satisfy NESA policy requirements with minor edits.' },
      { p: 'The implication: if you have a current ISO 27001 certificate, you are already most of the way to NESA on the technical side. The work that remains is mostly mapping, evidence formatting and a handful of UAE-specific overlays.' },
      { h2: 'Where they diverge (the 30 percent that actually matters)' },
      { p: 'The divergences are not random. They cluster in specific areas, and these are the areas where most ISO-first organisations find themselves doing two months of unplanned work to close out NESA.' },
      { p: 'Sector-specific overlays. NESA expects sector-specific controls layered on top of the baseline framework. Banking entities additionally comply with UAE Central Bank IBR (which overlaps NESA roughly 80 percent but adds payment systems and incident reporting requirements). Telecom entities answer to TDRA. Energy entities to ADNOC GRP. Healthcare entities to DOH or DHA. ISO 27001 has no equivalent sector layering — you build a generic ISMS, you certify, you are done. NESA assumes your regulator may pull on the thread differently than your neighbour’s regulator.' },
      { p: 'UAE-specific data residency and classification. NESA expects certain data classes to remain in UAE jurisdiction and uses a UAE-specific classification scheme. ISO 27001 expects you to have a classification scheme but is agnostic about its content. Most ISO-first organisations have to retrofit the UAE classification labels onto an existing scheme — straightforward work but easy to miss.' },
      { p: 'Personnel security and clearance. NESA, particularly for government and energy entities, expects vetting of personnel with access to sensitive systems against UAE-specific clearance regimes (most often through FAHR for federal entities). ISO 27001 expects background checks proportionate to risk and stops there. The vetting workflow is one of the slowest path-items on a NESA programme and almost never exists in an ISO-only environment.' },
      { p: 'Evidence formatting and the IAMM questionnaire. The NESA audit evidence pack is structured to the Information Assurance Maturity Model, a 0-to-5 scoring scheme across every control. The audit walks through the questionnaire methodically. ISO audits are more conversational and follow the auditor’s focus areas. Even when the underlying controls are identical, NESA evidence has to be reformatted into the IAMM structure. This is unglamorous work and is the single biggest reason ISO-first organisations underestimate the NESA workload.' },
      { p: 'Continuous controls operation and quarterly attestation. ISO 27001 expects annual surveillance audits and a three-year recertification cycle. NESA expects quarterly evidence refresh and continuous controls operation against sector regulator reporting cycles. The control content is similar; the operational tempo is heavier.' },
      { p: 'Regulator engagement model. ISO 27001 is audited by a third-party certification body of your choosing. NESA audits route through your sector regulator with a more enforcement-oriented relationship. The reporting templates, the language and the escalation paths are different. Compliance teams used to ISO’s relatively benign audit experience are sometimes surprised by the more formal regulator dynamic in NESA.' },
      { h2: 'A side-by-side at the domain level' },
      { p: 'NESA management domains M1 to M6 (governance, risk, awareness, HR security, compliance, performance) align loosely with ISO 27001 clauses 4 to 10 plus Annex A people controls. About 80 percent overlap on content, 100 percent overlap on intent.' },
      { p: 'NESA technical domains T1 to T9 (asset management, physical, operations, communications, access control, third-party, acquisition and development, incident, continuity) align with ISO 27001 Annex A technical and organisational controls. About 75 percent overlap on content. The divergences are in the granularity — NESA prescribes more, ISO leaves more to risk-based interpretation.' },
      { p: 'The cleanest way to see this is to lay a NESA control selection next to an ISO 27001 Statement of Applicability for the same organisation. The dual-mapped spreadsheet is the working artefact a sensible compliance lead maintains throughout the programme. Most of our engagements deliver a master control matrix on day one of remediation, and every control gets a NESA reference, an ISO reference and a single evidence locator. One control, one evidence pack, two compliance outcomes.' },
      { h2: 'Which to do first if you can only pick one' },
      { p: 'If you operate in a UAE critical sector and have not done NESA, do NESA first. It is mandatory. ISO 27001 is voluntary. Spending compliance budget on ISO before NESA when NESA is what your regulator will ask about is the wrong order.' },
      { p: 'If you operate internationally, sell to multinational customers or take part in cross-border tenders, ISO 27001 carries weight that NESA does not. The certificate opens commercial doors. In that case the right answer is: do NESA first because it is mandatory, then chain ISO 27001 into the back half of the programme using the work you already did.' },
      { p: 'If you have a current ISO 27001 certificate and a NESA audit notice, the order is forced. Start NESA gap assessment immediately, use the ISO ISMS as your foundation, and budget for the 30 percent divergence work.' },
      { p: 'If you have neither, are in a critical sector, and have a 12-month runway: run them as one combined programme. Total cost is roughly 1.2 to 1.4 times a single framework instead of 2 times two separate programmes. This is the option most clients eventually take once they see the dual-mapped control matrix.' },
      { h2: 'How to run them as one programme' },
      { p: 'Single control matrix from day one. Every control has a NESA reference, an ISO 27001 Annex A reference, an owner, an evidence locator, a test frequency and a maturity score. This is the artefact the programme runs from.' },
      { p: 'Single policy framework. Information security policy, acceptable use, classification, incident response, BCP, third-party, change management — written once, mapped to both frameworks in the document footer. No duplicate policies.' },
      { p: 'Single evidence repository. One folder structure, one tagging scheme, one evidence refresh cadence. Both auditors pull from the same source. The IAMM-formatted evidence packs are generated from the repository for NESA; the ISO Annex A evidence index is generated for ISO.' },
      { p: 'Sequenced audit windows. NESA audit first, in roughly month 8 to 10 of the programme. ISO 27001 stage 1 audit immediately after, ISO stage 2 audit a few months later. The NESA programme leaves the organisation in an ISO-ready posture by default.' },
      { p: 'A single steering committee, a single risk register, a single change pipeline. Two separate compliance programmes inside the same organisation will diverge within a quarter, and once they diverge the cost goes up sharply. Run one programme.' },
      { h2: 'Common mistakes' },
      { p: 'Treating ISO 27001 as a shortcut to NESA. It is a foundation, not a shortcut. The 30 percent divergence work is not optional.' },
      { p: 'Hiring two different consultancies for the two frameworks. They will produce two different control matrices that mostly cover the same ground in slightly different language, and you will spend a quarter reconciling them. Use one team.' },
      { p: 'Underestimating evidence and process workload. The control implementation is the cheap part. The evidence repository, the named owners, the calendar-driven attestation and the regulator-facing reporting are 60 to 70 percent of a real NESA programme. Plan accordingly.' },
      { p: 'Aiming for ISO 27001 certification before getting the NESA gap assessment done. You will rebuild parts of the ISMS to satisfy NESA-specific requirements, which is a sunk cost on the original certification work.' },
      { p: 'Letting the frameworks compete. Inside the organisation, the security team is the same team, the controls are the same controls and the evidence is the same evidence. Treat the two frameworks as outputs, not as competing initiatives.' },
      { h2: 'Bottom line' },
      { p: 'NESA and ISO 27001 are not the same standard, but they are close enough that running them as one programme is almost always the right call for a UAE critical-sector enterprise. The 70 percent overlap is real. The 30 percent divergence is predictable and plannable. The mistake is treating them as two separate programmes with two separate budgets and two separate teams. The right answer is one control matrix, one policy framework, one evidence repository and one steering committee, with two compliance outcomes at the end.' },
      { p: 'If you are at the start of either, get the dual mapping done before you commit to a control selection. It will save more time than any other single decision in the programme.' },
      { cta: { text: 'See how IP Care runs end-to-end NESA compliance programmes →', href: '/services/cybersecurity/nesa-compliance', label: 'NESA Compliance Services' } },
      { cta: { text: 'Already have a 90-day audit window? Read the emergency NESA playbook →', href: '/blog/nesa-compliance-90-days', label: 'Related: NESA in 90 Days' } },
    ],
  },
  {
    slug: 'inside-a-nesa-audit',
    title: 'Inside a NESA Audit: A 5-Day Walkthrough of What Actually Happens',
    category: 'Cybersecurity',
    author: 'Attique Bhatti',
    date: 'May 12, 2026',
    readTime: '14 min',
    excerpt: 'A day-by-day account of what a real NESA / UAE IAS audit looks like — who attends, what evidence they ask for, what separates a clean audit from a messy one.',
    img: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7',
    body: [
      { h2: 'Why most teams misunderstand the audit' },
      { p: 'The most common misconception about a NESA audit is that it is a technical inspection. It is not. It is an evidence inspection. The auditor is not there to test whether your firewall blocks the right ports — they assume it does. They are there to test whether you can prove the firewall is configured to a defined standard, that the configuration is reviewed on a documented cadence, that exceptions are logged, that the engineer responsible is named, that the change history is auditable, and that all of this has been the case continuously since the last cycle.' },
      { p: 'Teams that prepare for the audit by hardening their technical environment in the last six weeks consistently underperform. Teams that prepare by hardening their evidence and their narrative consistently outperform. The technical work matters — but it is necessary, not sufficient. This post walks through what an actual NESA audit looks like, day by day, so the preparation work you do is the work that actually shows up in the audit room.' },
      { p: 'The walkthrough below is generalised from real audits we have supported across banking, energy, government and healthcare clients. The exact shape varies by sector regulator and organisation size — a federal government entity audit is structured differently than a mid-size DOH-licensed healthcare provider — but the broad pattern is consistent.' },
      { h2: 'Before the audit week begins' },
      { p: 'NESA audits do not appear without warning. The sector regulator notifies you, typically 60 to 90 days in advance. The audit team — usually two to four assessors from a regulator-approved audit firm — issues an Information Assurance Maturity Model (IAMM) questionnaire roughly 30 days before the on-site visit. The questionnaire scores each applicable control on a 0 to 5 maturity scale and requires supporting evidence references.' },
      { p: 'The IAMM submission is the single most important pre-audit deliverable. It frames the entire on-site week. Auditors arrive having already read your self-assessment, decided which areas to probe and which to accept, and prepared their evidence sampling list. A well-prepared IAMM submission shortens the audit. A weak one extends it and shifts the auditor’s posture from verification to investigation — which is a meaningfully harder audit to pass.' },
      { p: 'In the week before the audit, the internal team should rehearse. Run a tabletop walkthrough with control owners presenting their controls aloud, exactly as they will in the audit room. The first attempt almost always reveals which owners are uncertain about their own controls. Fix that before the auditor sees it.' },
      { h2: 'Day 1 — Opening, scope confirmation, governance walkthrough' },
      { p: 'The audit week opens with a kickoff meeting attended by the audit team, the CISO or equivalent, the compliance lead, the IT director and typically the internal audit function. The auditor confirms scope, methodology, the daily agenda and the closing meeting timing. This sounds procedural but is the single most important meeting of the week: scope creep originates here, and so does scope discipline.' },
      { p: 'The rest of Day 1 covers the management domains (M1 to M6) — governance, risk management, awareness, human resources security, compliance and performance evaluation. The auditor wants to see the information security policy, the risk register, the awareness training records, the compliance calendar and the performance metrics dashboard. They will ask for the dates of recent management reviews, the attendees, and the decisions that came out of them.' },
      { p: 'A clean Day 1 establishes the auditor’s trust early. The control narratives sound rehearsed but not scripted. The documents are dated, owned and recently reviewed. The risk register is alive, not a 2022 PDF. When the auditor asks "when did the executive committee last review the security programme", the answer is a specific date with attendance and minutes — not a vague "regularly".' },
      { h2: 'Day 2 — Asset management, physical security, operations' },
      { p: 'Day 2 enters the technical domains. The auditor opens with asset management (T1) and physical security (T2). Asset management is where most first audits go sideways. The auditor will pick three sample assets from your inventory and ask to walk to them. If the inventory says you have a particular server in a particular rack and the rack is empty, the conversation gets uncomfortable fast.' },
      { p: 'Operations management (T3) covers backup, patching, configuration management, vulnerability management and capacity planning. Expect detailed evidence requests: the last 30 days of patch deployment reports, the most recent backup restoration test, the vulnerability scan results from last month with the remediation status of high and critical findings, and the change management approvals for the largest recent infrastructure change.' },
      { p: 'The pattern across Day 2 is sampling. The auditor does not review every control end to end — they sample evidence and trace it back to the control. A common technique: pick a high-severity vulnerability from a recent scan, ask who owns it, when it was discovered, when remediation was scheduled, when it was fixed, and what evidence proves it was fixed. If any one of those answers is missing, the control is scored down regardless of the underlying technical state.' },
      { h2: 'Day 3 — Communications, access control, third-party' },
      { p: 'Day 3 covers communications security (T4), access control (T5) and third-party security (T6). Communications security walks through network segmentation, encryption in transit, secure remote access and DNS security. Auditors increasingly ask for evidence of segmentation testing — not just "we have VLANs", but "here is the result of the last quarterly segmentation test that confirms the segmentation actually works".' },
      { p: 'Access control is the most documentation-heavy domain in the framework. Joiner, mover and leaver workflows, privileged access management, MFA enforcement, access reviews, service accounts, emergency access, session recording. Expect sample-based testing: the auditor picks three recent leavers and asks to see when their access was revoked across all systems with a timestamp. This is the test that fails most often. Leaver access revocation is theoretically immediate; in practice it is often delayed for one to two weeks, particularly for SaaS applications managed outside central IT.' },
      { p: 'Third-party security covers vendor risk management, contractual security clauses, vendor access controls, vendor incident reporting and the vendor onboarding and offboarding workflow. The audit here usually surfaces gaps in the vendor inventory: vendors with environment access who never went through formal onboarding, contracts that pre-date the current security policy, and offboarding workflows that exist on paper but have never been executed.' },
      { h2: 'Day 4 — Acquisition and development, incident management, continuity' },
      { p: 'Day 4 covers systems acquisition and development (T7), information security incident management (T8) and business continuity (T9). Acquisition and development is short in most organisations — secure development lifecycle, security testing in releases, third-party code review. Banking and government audits go deeper here than other sectors.' },
      { p: 'Incident management is one of the most heavily tested areas. The auditor will ask for the incident register — usually a 12 to 24 month view — and sample two or three incidents to trace through the lifecycle: detection, classification, response, containment, eradication, recovery, lessons learned and reporting to the regulator where required. The reporting timing is critical. UAE Central Bank and TDRA both have specific incident reporting windows that, if missed, become audit findings in their own right regardless of how well the incident itself was handled.' },
      { p: 'Business continuity is the area where evidence and reality diverge most often. Almost every organisation has a BCP document. Far fewer have evidence of a real tabletop or live recovery exercise in the last 12 months. The auditor wants to see the exercise log, the participant list, the scenarios tested, the outcomes and the post-exercise improvement plan. If the BCP has not been exercised, it has not been validated, regardless of how thorough the document looks.' },
      { h2: 'Day 5 — Closing meeting, findings, next steps' },
      { p: 'Day 5 morning is reserved for clarifications, follow-up evidence requests and any controls the auditor wants to re-examine. The closing meeting in the afternoon is where the audit team presents preliminary findings, scored against the IAMM. Final findings are issued in a formal report 2 to 4 weeks later, but the closing meeting tells you almost everything you need to know.' },
      { p: 'Findings are usually categorised as major (significant control failures that require formal remediation plans and regulator notification), minor (lower-severity gaps with shorter remediation timelines) and observations (advisory items, not enforced but tracked). The goal is zero majors, manageable minors and a credible response plan for both.' },
      { p: 'The closing meeting is also where the next audit cycle is anchored. Most NESA audits run annually with surveillance touchpoints in between; some sectors run more frequently. The dates set in the closing meeting drive the next 12 months of compliance calendar planning.' },
      { h2: 'What separates a clean audit from a messy one' },
      { p: 'Five patterns consistently separate the audits we see go well from the ones that drag.' },
      { p: 'Named control owners who can speak to their controls without notes. Auditors mark down ambiguity. They mark up specificity. An owner who says "the privileged access policy is reviewed every six months by me, last reviewed on March 14, here are the meeting minutes" outperforms one who says "yes, we review it regularly". The content is the same; the audit experience is not.' },
      { p: 'A single evidence repository with consistent naming and dating. Auditors waste time searching for evidence. They mark organisations down for it. A well-organised SharePoint, Confluence or evidence platform with date-stamped controls in a consistent folder structure is one of the highest-leverage pre-audit investments you can make.' },
      { p: 'A live IAMM submission, not a one-time document. Organisations that maintain the IAMM as a living artefact between audits walk into the next cycle 80 percent prepared. Those that rebuild it from scratch each cycle pay the full preparation cost every time.' },
      { p: 'A culture of recent evidence. Auditors do not penalise evidence that is "old" if the control runs on an annual cadence. They penalise evidence that is stale relative to its defined frequency. If your patch review is supposed to be monthly and the last evidence is from three months ago, that is a finding. Define the cadence and meet it.' },
      { p: 'A relationship with the auditor, not just a transaction. Auditors are professionals doing a job. Treating them with respect, answering questions directly, and not arguing every finding produces better outcomes. Arguing every minor finding to defend internal politics costs goodwill that you spend later when a closer call goes against you.' },
      { h2: 'Common surprises' },
      { p: 'The SaaS shadow IT problem. Almost every organisation discovers in their first audit that the asset and access inventories miss several SaaS applications, often containing significant data, that were procured outside central IT. The fix is straightforward but takes time: a SaaS discovery exercise, formal onboarding into the control framework and ongoing identity-driven discovery via cloud access security broker tooling.' },
      { p: 'The leaver access problem. Even mature organisations rarely revoke access cleanly within the required window across every system. The fix is identity-driven joiner-mover-leaver automation, not stronger HR-to-IT handoff processes.' },
      { p: 'The contractor and third-party access problem. Auditors increasingly probe long-running third-party access — vendors who were granted access three years ago and still have it, often for a contract that ended.' },
      { p: 'The board reporting problem. Many organisations cannot produce dated, attended minutes of executive committee security reviews on demand. The auditor will ask, and "we discuss it informally in the leadership team" is not an answer that scores well.' },
      { h2: 'Bottom line' },
      { p: 'The NESA audit is structured, predictable and largely about evidence. The preparation that pays off is not last-minute technical hardening — it is named owners, dated evidence, defined cadences and a rehearsed narrative. Organisations that invest in those four things consistently walk into the audit room with the auditor’s default disposition being verification rather than investigation, and that is the single biggest factor in how the week goes.' },
      { p: 'For the next cycle, start the day after the closing meeting. Capture every finding, observation and improvement opportunity in a working plan. Maintain the IAMM as a living document. Run quarterly internal control reviews against it. The compounding effect over two or three cycles is real: each audit becomes shorter, the findings smaller, and the operating burden lower.' },
      { cta: { text: 'See how IP Care runs end-to-end NESA compliance and audit support →', href: '/services/cybersecurity/nesa-compliance', label: 'NESA Compliance Services' } },
      { cta: { text: 'Want the framework comparison? Read NESA vs ISO 27001 →', href: '/blog/nesa-vs-iso-27001', label: 'Related: NESA vs ISO 27001' } },
      { cta: { text: 'Working a 90-day audit window? The emergency NESA playbook →', href: '/blog/nesa-compliance-90-days', label: 'Related: NESA in 90 Days' } },
    ],
  },
  {
    slug: 'cctv-installation-cost-dubai',
    title: 'CCTV Installation Cost in Dubai (and the UAE): A 2026 Pricing Guide',
    category: 'ELV & Security',
    author: 'IP Care Team',
    date: 'May 12, 2026',
    readTime: '15 min',
    excerpt: 'Why two CCTV quotes can vary 5× for the same building — and what an honest 4, 16, 32 and 64-camera installation actually costs in AED, with SIRA, ADMCC, retention and AMC included.',
    img: 'https://images.unsplash.com/photo-1557804506-669a67965ba0',
    body: [
      { h2: 'Why CCTV quotes vary 5× for the same job' },
      { p: 'A common scenario: a Dubai office facilities manager asks four vendors to quote a 16-camera CCTV installation. The cheapest comes back at AED 18,000. The most expensive comes back at AED 95,000. The mid-range two are AED 32,000 and AED 48,000. All four claim to deliver "16 IP cameras, NVR and installation". The vendor responses to the question "why are you 5× higher than your cheapest competitor" usually do not answer the question well.' },
      { p: 'The honest answer is that "16 cameras and an NVR" is not a specification. It is a category. Inside that category, the camera resolution, the storage retention, the cabling type, the power method, the installer certification, the regulatory approvals, the brand quality, the analytics and the support model can each change the cost by 30 to 200 percent. The 5× spread is real and is not always price gouging — it is often scope ambiguity. This guide explains what the cost drivers actually are, how much each contributes, and what an honest CCTV installation should cost in Dubai and across the UAE in 2026.' },
      { p: 'Numbers below are in UAE Dirhams and reflect typical pricing seen across mid-market commercial installations in Dubai, Abu Dhabi and Sharjah in the first half of 2026. They are indicative ranges, not fixed quotes — but they are the ranges a buyer should expect a credible vendor to fall inside.' },
      { h2: 'The five cost drivers that actually matter' },
      { p: 'Five things move the cost of a CCTV installation more than anything else. Most marketing material talks about "advanced features" and "AI-powered analytics". In practice the price-shaping factors are more pedestrian and more decisive.' },
      { p: 'Camera count and resolution. The most obvious driver. Camera count is linear; resolution is roughly logarithmic in cost. Going from 2 megapixel to 4 megapixel cameras typically adds 30 to 50 percent per camera. Going to 8 megapixel adds another 40 to 70 percent on top. For most general surveillance, 4 megapixel cameras are the sensible sweet spot. 8 megapixel is justified where licence-plate recognition, large-area coverage or evidentiary face capture is required.' },
      { p: 'Cabling, conduit and labour. In a new-build property where cable trays and conduit are accessible, cabling labour is straightforward. In an occupied office with finished ceilings, the cabling labour can easily double the per-camera installed cost. Concrete walls, marble cladding and access-restricted floors all multiply the labour. Most quote variance between vendors is hidden in this line item.' },
      { p: 'Storage and retention period. The Dubai Police recommendation for commercial CCTV is a minimum of 30 days retention. Some sectors require 90 days. Specific properties — banks, gold souks, certain government locations — require 180 days or more. Each step up in retention requires substantially more disk. For a 16-camera 4 megapixel system, 30-day retention is roughly 16 to 24 terabytes of usable storage; 90 days is 50 to 70 terabytes. Storage and the NVR/server class it runs on is often 15 to 25 percent of the total installation cost.' },
      { p: 'Brand and certification. The price gap between Hikvision/Dahua-class cameras (volume manufacturers, very capable, dominant market share globally and in the UAE) and Axis/Bosch-class cameras (premium tier, longer warranty, stronger analytics, higher build quality) is typically 2 to 4× per camera. Mid-tier brands like Hanwha, Uniview and Avigilon sit between the two. The cheapest tier — generic and unbranded cameras sold on price alone — usually saves 30 to 40 percent up front and loses it back in failure rates and lack of vendor support within two to three years.' },
      { p: 'Regulatory approval and certified installer. In Dubai, commercial CCTV installations must be carried out by a Security Industry Regulatory Agency (SIRA) approved contractor and the design submitted for SIRA approval. Abu Dhabi has equivalent requirements through the Abu Dhabi Monitoring and Control Centre (ADMCC), operated by Abu Dhabi Police. These approvals carry real cost — both the approval process itself and the requirement that the installation team carry individual installer credentials certified by the relevant authority. IP Care is SIRA-licensed in Dubai and ADMCC-certified in Abu Dhabi, which is the baseline a commercial property should expect from any installer it engages. Vendors who quote without SIRA or ADMCC pricing built in are quoting an installation you cannot legally operate as a commercial property in either emirate.' },
      { h2: 'Indicative pricing by installation size' },
      { p: 'The ranges below assume mid-tier IP cameras (Hikvision Pro, Dahua Ultra, Hanwha Wisenet or equivalent), 4 megapixel resolution, 30-day retention, SIRA (Dubai) or ADMCC (Abu Dhabi) approval included, professional installation with conduit where required, and a 12-month warranty with 8x5 support. They do not include sales tax, ongoing AMC, or sector-specific overlays.' },
      { p: 'Small office or villa, 4 cameras with 4-channel NVR. Typical scope: building entrance, reception or hallway, two perimeter or outdoor zones, 4-channel NVR with 4 TB storage. Indicative cost: AED 6,500 to AED 12,000 fully installed. Most of the variance is cabling — a new-build villa might come in at AED 6,500; a finished office on the eighth floor of a Business Bay tower might be AED 11,000 to 12,000.' },
      { p: 'Standard SME office, 8 to 12 cameras. Typical scope: full perimeter coverage of a 200 to 400 square metre office, reception desk, meeting rooms, server room and corridors, 16-channel NVR with 8 to 16 TB storage. Indicative cost: AED 14,000 to AED 28,000. Conduit-heavy retrofit installations push to the upper end of this range; clean new-build installations sit at the lower end.' },
      { p: 'Mid-size commercial premises, 16 to 24 cameras. Typical scope: a full-floor office or small retail outlet, all entry and exit points, key internal areas, parking, perimeter, 32-channel NVR with 24 to 48 TB storage and a redundant power supply. Indicative cost: AED 32,000 to AED 65,000. The wider range here reflects the much wider variance in cabling labour at this scale.' },
      { p: 'Larger commercial or light industrial, 32 to 48 cameras. Typical scope: multi-floor offices, warehouses, large retail or showrooms with parking and yard coverage, 64-channel NVR cluster or VMS server, 60 to 100 TB storage, redundant power, often paired with intercom and access control integration. Indicative cost: AED 70,000 to AED 160,000.' },
      { p: 'Enterprise multi-site or specialised, 64 to 128 cameras. Typical scope: a single large building (hotel, mall section, hospital, industrial facility), 128-channel VMS, dedicated CCTV server room or rack, 120 to 250 TB storage, network segmentation, integration with access control and intrusion alarms, on-site monitoring station. Indicative cost: AED 180,000 to AED 480,000.' },
      { p: 'Large enterprise, 200+ cameras, multi-site. Typical scope: enterprise VMS (Milestone, Genetec or Avigilon), centralised storage with multi-site replication, redundancy at every layer, dedicated network for CCTV traffic, structured cabling refresh, full integration with security operations centre. Indicative cost: AED 600,000 upwards, often AED 1.5 million to AED 4 million for large hotels, malls and industrial facilities. At this scale, fixed-price scoping is rare — proper installations are quoted after a detailed site survey.' },
      { h2: 'UAE regulatory cost: SIRA, ADMCC and certified installation' },
      { p: 'Most buyers underestimate the regulatory layer. In Dubai, the SIRA requirement is not a recommendation — it is a licence condition for the property. A commercial premises operating CCTV without SIRA-approved design and certified installation is operating outside compliance, and renewal of the trade licence can be affected. SIRA approval typically adds AED 3,000 to AED 12,000 to a mid-size project depending on scope, plus the requirement to use SIRA-certified installers (which is usually rolled into the labour line).' },
      { p: 'Abu Dhabi works through the Abu Dhabi Monitoring and Control Centre (ADMCC), operated by Abu Dhabi Police, with broadly similar requirements: certified contractor, approved design, post-installation handover documentation and live connectivity to the central monitoring infrastructure for certain premises. IP Care holds active ADMCC certification, which is the credential a commercial property in Abu Dhabi should look for in any CCTV installer. Sharjah and the Northern Emirates have lighter regulatory regimes for non-critical premises but heavier ones for hotels, banks and government-adjacent properties. Sector-specific overlays are also common: hotels of certain star ratings, healthcare facilities, financial services premises and educational institutions all carry their own minimum CCTV specifications layered on top of the general SIRA or ADMCC framework.' },
      { p: 'A credible CCTV quote should explicitly itemise: SIRA or ADMCC approval fees, the certifications held by the installation team (including the individual installer credential reference numbers), the design submission process, and the post-installation handover documentation including SIRA-stamped or ADMCC-approved drawings. If these items are absent from the quote, they are either being absorbed at the vendor’s cost (rare, ask twice) or they are being skipped — which is the typical scenario at the cheap end of the market.' },
      { h2: 'The hidden costs nobody quotes for' },
      { p: 'Beyond the headline installation, several recurring costs are often left out of the initial quote and surface later as project overruns or ongoing operational expenses.' },
      { p: 'Annual maintenance contracts. A proper AMC covers preventive maintenance visits, firmware updates, camera cleaning, focus checks, NVR health monitoring, storage validation and break-fix labour. Typical AMC pricing in the UAE is 8 to 15 percent of the initial installation value per year. Cheap installations often quote a 1-year warranty and no AMC; year two onwards, the property either pays per-call rates or absorbs the failure risk.' },
      { p: 'Storage replacement. Surveillance-grade hard drives have a 3 to 5 year duty cycle. A 100 TB array represents AED 30,000 to AED 60,000 of disk that will need replacement over the system lifetime. Building this into a 5-year cost model is the difference between an installation that ages gracefully and one that quietly fails.' },
      { p: 'Power and UPS. CCTV systems should be on UPS or generator-backed power to remain functional during outages — the surveillance window during a power event is often the most important one. A modest UPS for an SME-scale system adds AED 3,000 to AED 8,000. Enterprise installations with on-site monitoring rooms typically require dedicated power infrastructure that adds materially to the total.' },
      { p: 'Cabling and conduit overruns. In retrofit projects, cabling estimates assume access. Discovered concrete cores, asbestos in older buildings, leased-floor access restrictions and tenant-coordination delays can each add 10 to 30 percent to labour. A well-priced retrofit quote builds a contingency for these. A cheap quote does not, and the overruns become change requests during installation.' },
      { p: 'Future expansion headroom. NVRs are sized for current cameras plus typically 25 percent headroom. Storage is sized for the chosen retention plus a similar margin. Quotes that size both to the exact current need save money up front but force a full hardware refresh when the camera count grows. Sensible quotes specify the headroom explicitly and price it.' },
      { p: 'Analytics and VMS licensing. Basic video management is bundled with the NVR. Advanced analytics — licence plate recognition, people counting, heat mapping, intrusion detection, AI-driven event filtering — are usually per-camera-per-year licensing. A 32-camera enterprise installation with LPR on 8 cameras and AI analytics on 16 might carry AED 8,000 to AED 18,000 per year in licensing on top of hardware.' },
      { h2: 'How to read a CCTV quote' },
      { p: 'A defensible quote should answer six questions clearly, in writing, before you sign anything. Most quotes in the UAE answer two or three. Asking for the missing four is the single most effective filter for separating credible vendors from price-only operators.' },
      { p: 'One. What is the camera model, resolution, lens type and image sensor for each location? "16 IP cameras" is not an answer — model and SKU is. The camera sensor matters more than the resolution headline.' },
      { p: 'Two. What is the recording retention in days, and what storage capacity supports it? The retention claim should be backed by a calculated storage figure assuming average motion-triggered recording or 24/7 recording, whichever is specified. Round numbers like "30 days" without a TB figure are vendor optimism.' },
      { p: 'Three. Is SIRA (Dubai) or ADMCC (Abu Dhabi) approval included in the scope, and which installer certifications are held by the team? Ask for the approval timeline. Ask for the certification reference numbers. A reputable vendor — IP Care included — provides both within an hour of the request.' },
      { p: 'Four. What does the cabling scope assume, and what triggers a change request? Specifically: how many metres of cabling are budgeted, what conduit type is included, and what is the per-metre rate for additional cabling discovered during installation?' },
      { p: 'Five. What is the support model after installation? Free during the warranty period is the baseline. Ask for the AMC pricing, the response time SLA, the engineer availability hours and whether spare hardware is held on site. The answer should be specific.' },
      { p: 'Six. What is the handover documentation? At minimum: SIRA-stamped drawings (for Dubai) or ADMCC-approved drawings (for Abu Dhabi), as-built network and power diagrams, camera location plans with field-of-view diagrams, NVR and VMS administrative credentials, firmware version inventory, AMC contract and warranty cards. Properties operating without this documentation lose the ability to maintain or audit the system meaningfully a year later.' },
      { h2: 'When to go cheap, when to pay premium' },
      { p: 'Not every installation justifies premium spend. The right tier depends on three things: what the cameras are protecting, how long the property will operate the system, and how the footage will be used.' },
      { p: 'A small office, 24 to 36 month lease, deterrent and basic incident review only — mid-tier brand, 2 to 4 megapixel cameras, 30-day retention, SIRA or ADMCC compliant installation, 1-year warranty. Going premium adds cost without proportional benefit.' },
      { p: 'A multi-tenant commercial building, owner-operated, 10-plus year operating horizon — premium tier on outdoor and key interior cameras, mid-tier on lower-traffic zones, longer retention, full AMC, integration with access control. The lifetime cost favours quality.' },
      { p: 'High-value or regulated environments — banks, jewellery retail, healthcare facilities, government-adjacent properties, hotels — premium tier across the board, certified analytics, longer retention, redundant storage, integration with on-site or off-site monitoring. The cost of an incident the system fails to capture exceeds the cost of premium specification by orders of magnitude.' },
      { p: 'Industrial and warehousing — specification depends on the asset value and the operational risk profile. The lowest-tier IP cameras are usually false economy because outdoor environmental tolerance, motion handling and analytics quality all degrade visibly.' },
      { h2: 'Bottom line' },
      { p: 'CCTV is a regulated, technical purchase that looks deceptively simple in the quote stage. The difference between an installation that does the job and an installation that fails during the one event it was bought to capture is often not visible at the quote level. It is visible in the camera specification, the storage sizing, the regulatory compliance and the support model.' },
      { p: 'For a Dubai or wider UAE buyer, the practical ranges are: AED 6,500 to 12,000 for a 4-camera small office or villa, AED 14,000 to 28,000 for an 8 to 12-camera SME, AED 32,000 to 65,000 for 16 to 24 cameras, AED 70,000 to 160,000 for 32 to 48 cameras, AED 180,000 to 480,000 for 64 to 128 cameras, and AED 600,000 upwards for true enterprise scale. Vendors quoting below these ranges are usually omitting SIRA or ADMCC approval, retention sizing, AMC, certified installation, or all of the above.' },
      { p: 'The best filter is the six questions above. Vendors who answer them in writing are vendors operating on a different standard than the headline-price market. Vendors who do not — politely, repeatedly — are usually quoting an installation that is cheaper for a reason.' },
      { cta: { text: 'See how IP Care designs and installs SIRA and ADMCC-compliant CCTV across Dubai and Abu Dhabi →', href: '/services/elv/cctv-systems', label: 'CCTV Systems Service' } },
      { cta: { text: 'Looking for the broader ELV picture? CCTV is one of six ELV categories we cover →', href: '/services/elv', label: 'ELV & Physical Security' } },
      { cta: { text: 'Integrated security: CCTV pairs with access control for a complete physical security layer →', href: '/services/elv/access-control', label: 'Related: Access Control' } },
    ],
  },
  {
    slug: 'event-wifi-pricing-reality',
    title: 'Event WiFi That Does Not Crash: A Pricing & Planning Reality Check',
    category: 'Event IT',
    author: 'Rahul Kapoor',
    date: 'Apr 17, 2026',
    readTime: '8 min',
    excerpt: 'Why a quote for "event WiFi" can vary 10× between vendors — and what an honest scope conversation actually looks like.',
    img: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30',
    body: [
      { h2: 'Why quotes vary 10×' },
      { p: 'One vendor quotes AED 25,000. Another quotes AED 250,000. Both are pitching "event WiFi" for the same venue. The gap is not greed — it is scope. Most cheap quotes assume you do not need redundancy, do not need on-site engineers, and do not really care if the network drops during the keynote. Most expensive quotes assume you do.' },
      { h2: 'The real cost drivers' },
      { p: 'Three things move the price more than anything else: concurrent user density, redundancy level, and on-site engineering hours.' },
      { p: 'Concurrent users: a 500-person conference with corporate-grade WiFi is not the same as a 5,000-person event where every attendee is streaming. The latter needs three to five times more access points per square metre.' },
      { p: 'Redundancy: single uplink, dual uplink, or fully diverse path? Single APs or paired redundant pairs? Hot-swap controllers or single controller? Each step roughly doubles the kit cost.' },
      { p: 'On-site engineers: a single engineer for setup-only is cheap. A tiered on-site team during the event is not. If your event runs ten hours per day for three days, expect 60+ engineer-hours just on-site, before remote NOC support.' },
      { h2: 'What an honest scope conversation looks like' },
      { p: 'It starts with how many people, doing what, for how long. Then: what is the cost of a 30-minute network outage during the event? That number determines redundancy level. Then: when does the venue open for setup, when must the event be live? That determines team size and shift count.' },
      { h2: 'Where vendors cut corners' },
      { p: 'Predictive RF design skipped. Single-radio APs in a venue that needs dual-radio. No spare controller. Bandwidth contracted on a residential-grade circuit. One engineer running three venues at once. Each of these saves money up front and creates the failure that ruins the event.' },
      { h2: 'A reasonable ask' },
      { p: 'When you receive a quote, ask three things: how many APs and what model, what is the redundancy at the controller and uplink, and how many engineer-hours are budgeted. If a vendor cannot answer those quickly, the quote is built on assumptions you have not seen.' },
    ],
  },
  {
    slug: 'ipad-kiosk-deployment-playbook',
    title: 'iPad Kiosk Deployments: The Configuration Playbook',
    category: 'Rentals',
    author: 'Sarah Chen',
    date: 'Apr 09, 2026',
    readTime: '7 min',
    excerpt: 'Single-app kiosks, MDM enrolment, lockdown profiles and what to set up before delivery so day-of-event runs cleanly.',
    img: 'https://images.unsplash.com/photo-1561154464-82e9adf32764',
    body: [
      { h2: 'Why kiosks fail on day one' },
      { p: 'Most iPad kiosk failures at events are not hardware failures. They are configuration failures. An attendee finds the home button. An admin password is the default. An app crashes and there is no kiosk-mode auto-restart. The fixes are simple — but they have to happen before delivery, not at the registration desk on day one.' },
      { h2: 'The pre-delivery checklist' },
      { p: 'Single App Mode enabled via Apple Configurator or MDM. Guided Access as backup if the deployment uses unmanaged devices. Auto-lock disabled or set to "Never". Notifications disabled — including from the kiosk app itself. Screen Time and Restrictions configured so the home button, control centre, and side switches do nothing.' },
      { p: 'Network: pre-configured WiFi profile with the event SSID and password, plus a fallback SSID. Cellular if the device supports it, with a SIM that has data — not just emergency calling.' },
      { h2: 'MDM enrolment' },
      { p: 'For more than five devices, MDM is mandatory. Jamf, Microsoft Intune, Mosyle and Kandji all do the job. The MDM should enforce the configuration, push the kiosk app, and provide remote wipe and lock. Without MDM you are configuring each device by hand — and missing one means it ships with the wrong build.' },
      { h2: 'Power and physical setup' },
      { p: 'Battery life matters more than people think. An iPad in always-on kiosk mode lasts four to six hours. For a ten-hour event, you need either always-plugged kiosks or a swap protocol with a charging station. Decide before the order ships.' },
      { p: 'Cases: locked stands prevent walking. Tethered cables prevent the iPad from leaving. Both pay for themselves the first time a guest "borrows" a device for a photo.' },
      { h2: 'The day-of failure mode you cannot test' },
      { p: 'One iPad locks up. The kiosk app crashes. The screen is white. The attendant cannot fix it. Your protocol should be: swap the device, take the broken one offline, debug later. Have spare devices on site. Always. We bring 10% spares as standard for events under 50 units, 5% above that.' },
    ],
  },
  {
    slug: 'aws-vs-azure-uae-enterprises',
    title: 'AWS vs Azure for UAE Enterprises: The Honest Comparison',
    category: 'Managed IT',
    author: 'Attique Bhatti',
    date: 'Mar 31, 2026',
    readTime: '12 min',
    excerpt: 'Both have UAE regions. Both have enterprise discounts. The decision usually comes down to four factors — and price is not one of them.',
    img: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa',
    body: [
      { h2: 'The honest framing' },
      { p: 'AWS and Azure are not the same product. They are also not as different as their sales teams will tell you. For most UAE enterprises, the right answer depends on four factors: existing identity stack, regulatory data residency, application portfolio, and the team you already employ.' },
      { h2: 'Factor 1 — Identity gravity' },
      { p: 'If your organisation runs Microsoft 365 and Entra ID, Azure has gravity. Conditional Access, Privileged Identity Management and single-sign-on integration are deeper out of the box. You can do all of this against AWS too — it just takes more configuration and more brittle glue.' },
      { p: 'If your identity is Okta or Google Workspace, the gravity is neutral.' },
      { h2: 'Factor 2 — Data residency and compliance' },
      { p: 'Both providers operate UAE-resident regions. AWS Middle East (UAE) opened earlier and has broader service coverage. Azure UAE North and Central regions cover the high-value services and have caught up rapidly. For most workloads either is fine; for some regulated services, only one of the two will have the specific service available in-region.' },
      { p: 'Check the service availability map before assuming. Do not assume.' },
      { h2: 'Factor 3 — Application portfolio' },
      { p: 'Greenfield containerised workloads run well on either. Lift-and-shift Windows estates with SQL Server, .NET and Exchange typically run cheaper and easier on Azure because the licensing economics favour it. Linux-heavy, open-source-heavy estates often feel more at home on AWS.' },
      { h2: 'Factor 4 — The team you already employ' },
      { p: 'This is the factor nobody talks about and the one that determines success. A team with three AWS certifications and zero Azure certifications will build a better AWS environment than an Azure environment, even if Azure was technically the better choice. Retraining takes 12 to 18 months. Plan accordingly.' },
      { h2: 'What the price difference really looks like' },
      { p: 'Sticker prices are within 5 to 10 percent of each other for equivalent workloads. Reserved instance and savings plan discounts are similar. The real cost variance comes from how well the team operates the platform — right-sizing, shutdown schedules, storage tiers, network egress. That variance can be 30 to 40 percent. The platform is the smaller lever.' },
      { h2: 'The boring conclusion' },
      { p: 'Pick the platform that fits your identity stack, your team, and your regulatory footprint. Pick the one you can operate well, not the one with the better launch announcement.' },
    ],
  },
]

export const getArticle = (slug) => articles.find(a => a.slug === slug) || null
export const getAllArticleSlugs = () => articles.map(a => a.slug)
