export const articles = [
  { slug: 'zero-trust-practical-guide', title: 'Zero Trust in 2026: A Practical Enterprise Roadmap', category: 'Cybersecurity', author: 'Attique Bhatti', date: 'Jun 12, 2026', readTime: '12 min', excerpt: 'What Zero Trust actually means in 2026 — and a 6-step roadmap you can start this quarter.', img: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5', body: [
    { h2: 'What Zero Trust actually means' },
    { p: 'Zero Trust is an architecture, not a product. It is a shift from perimeter-based trust to identity-centric, continuously verified access decisions. In 2026, the mature form of Zero Trust combines strong identity (MFA, conditional access, device posture), micro-segmentation (ZTNA, ZTWA), and continuous verification.' },
    { h2: 'The 6-step practical roadmap' },
    { p: 'Start with a CISA Zero Trust Maturity Model (ZTMM) scoring across five pillars: Identity, Device, Network, Application Workload and Data. Pick one pillar and one use-case that drives measurable value in 90 days — typically ZTNA for remote access or Conditional Access for identity. Then scale outward.' },
    { h2: 'Common pitfalls' },
    { p: 'The #1 mistake is treating Zero Trust as a vendor bake-off. Vendors matter, but architecture matters more. The second mistake is scope creep — trying to boil the ocean kills program momentum. Ship a beachhead use-case, measure outcomes, then scale.' },
  ] },
  { slug: 'stadium-wifi-72-hours', title: 'How We Powered a 50,000-Seat Stadium Network in 72 Hours', category: 'Event IT', author: 'Rahul Kapoor', date: 'May 28, 2026', readTime: '9 min', excerpt: 'Inside the planning, kit list and on-site playbook that delivered event WiFi for one of the region’s biggest sporting events.', img: 'https://images.unsplash.com/photo-1548092372-0d1bd40894a3', body: [
    { h2: 'The brief' },
    { p: 'A major sporting event. 72 hours from venue handover to kickoff. 50,000 fans, 2,000 press and production, plus a broadcast LAN. Our team had done this before — but never this fast.' },
    { h2: 'The kit' },
    { p: '220 HPE Aruba AP-635 WiFi 6E access points, 48 Ubiquiti PtP links, 12 core switches, a full temporary NOC in a 12U portable rack, and two 10 Gbps microwave uplinks to the broadcast compound.' },
    { h2: 'What went right' },
    { p: 'Predictive RF modelling (Ekahau). Pre-staged, pre-tested gear. A playbook from 30+ prior events. 18 engineers on site in shifts. Zero P1 incidents during the event.' },
  ] },
  { slug: 'finops-azure-cut-spend', title: 'FinOps for Mid-Market: Cutting Azure Spend by 34%', category: 'Managed IT', author: 'Sarah Chen', date: 'May 15, 2026', readTime: '11 min', excerpt: 'The FinOps playbook we ran with a mid-market SaaS client that delivered 34% Azure savings in 90 days.', img: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b', body: [{ p: 'Most cloud overspend is structural, not behavioural. Fix the structure first — right-sizing, Reserved Instances, and shutdown schedules deliver 70% of the gains with 30% of the effort.' }] },
  { slug: 'sase-vendor-evaluation', title: 'Evaluating SASE Vendors in 2026: A Practical Framework', category: 'Cybersecurity', author: 'Attique Bhatti', date: 'May 08, 2026', readTime: '14 min', excerpt: 'A vendor-neutral framework for choosing between Palo Alto, Zscaler, Netskope and Cisco SASE.', img: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3', body: [{ p: 'Start with integrations and starting point, not feature matrices. Feature parity is closer than anyone admits.' }] },
  { slug: 'wifi-7-real-world', title: 'WiFi 7 in the Real World: What’s Actually Different', category: 'Networking', author: 'Rahul Kapoor', date: 'Apr 28, 2026', readTime: '7 min', excerpt: 'We’ve deployed WiFi 7 in four venues this year. Here’s what’s genuinely different and what isn’t.', img: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f', body: [{ p: 'MLO (Multi-Link Operation) is the real story. The raw throughput numbers are less interesting than the latency behaviour.' }] },
  { slug: 'laptop-rental-vs-buy', title: 'Rent or Buy: The Real Math on Enterprise Laptops', category: 'Rentals', author: 'Sarah Chen', date: 'Apr 20, 2026', readTime: '6 min', excerpt: 'We ran the numbers across 20 client scenarios. When does renting actually beat buying?', img: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853', body: [{ p: 'For temporary projects under 18 months, rental wins consistently. Above 24 months, purchase with a 3-year refresh wins.' }] },
  { slug: 'elv-converged-security', title: 'Converged Security: Why ELV and Cyber Should Be One Team', category: 'Cybersecurity', author: 'Attique Bhatti', date: 'Apr 12, 2026', readTime: '10 min', excerpt: 'Your CCTV network is an IoT estate. Treat it accordingly — or expect to be the next breach story.', img: 'https://images.unsplash.com/photo-1557804506-669a67965ba0', body: [{ p: 'In most enterprises, the CCTV VLAN is the soft underbelly. Attackers know. Security teams rarely do.' }] },
  { slug: 'ipcare-nba-toronto', title: 'Case Study: NBA Global Games in Toronto', category: 'News', author: 'IP Care Team', date: 'Apr 02, 2026', readTime: '8 min', excerpt: 'Behind the scenes at the Scotiabank Arena: the network refresh that powered a global sporting event.', img: 'https://images.unsplash.com/photo-1563841930606-67e2bce48b78', body: [{ p: 'Over 20,000 fans per night. Live broadcast to 150+ countries. Zero network incidents across five days.' }] },
  { slug: 'xsiam-vs-legacy-siem', title: 'XSIAM vs. Legacy SIEM: When the Migration Makes Sense', category: 'Cybersecurity', author: 'Attique Bhatti', date: 'Mar 25, 2026', readTime: '13 min', excerpt: 'We’ve migrated three enterprises from Splunk to XSIAM this year. Here’s the decision framework.', img: 'https://images.unsplash.com/photo-1504384764586-bb4cdc1707b0', body: [{ p: 'The honest answer: it depends. But the dependencies are fewer than you’d think.' }] },
  {
    slug: 'choosing-managed-it-provider-uae',
    title: 'Choosing a Managed IT Provider in the UAE: 7 Questions to Ask',
    category: 'Managed IT',
    author: 'IP Care Team',
    date: 'May 05, 2026',
    readTime: '9 min',
    excerpt: 'Most MSP pitches sound identical. These seven questions surface the differences that actually matter once the contract is signed.',
    img: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d',
    body: [
      { h2: 'Why most MSP comparisons fail' },
      { p: 'Every managed IT provider in the UAE claims 24×7 support, SLA-backed response and certified engineers. On paper, they look the same. The real differences only show up after the contract is signed and the first incident hits.' },
      { p: 'These seven questions are designed to surface those differences before you sign. They are the ones we wish more clients asked us in their first meeting.' },
      { h2: '1. What does your P1 response look like — in numbers, last month?' },
      { p: 'Forget the SLA on paper. Ask for the actual P1 response time average from the previous month, with a sample of ticket IDs. Providers that publish this monthly are operating on a different level than those that quote a target.' },
      { h2: '2. Where do my tickets get answered, and by whom?' },
      { p: 'Offshore tier-one queues are not inherently bad — but you should know. Ask if your first responder will be UAE-based or routed offshore. Ask the experience level of that responder. Cheap MSPs hide this.' },
      { h2: '3. What happens if you miss the SLA?' },
      { p: 'A contract without service credits is a contract without consequences. Real SLAs come with financial credits when missed, written in plain language. If the response is "we never miss," walk away — that is marketing, not operations.' },
      { h2: '4. Show me your last quarterly business review for a similar client.' },
      { p: 'Quarterly reviews separate operators from order-takers. The good MSPs run them as a discipline — anonymised numbers, capacity trends, security posture, planned work. The bad MSPs invent one for the sales meeting and never run another.' },
      { h2: '5. How do you handle scope creep?' },
      { p: 'Every managed contract grows in scope. The question is how the MSP handles it. Transparent change requests with documented impact? Or quiet hours billed retrospectively? Ask for the change request template.' },
      { h2: '6. Who owns the relationship after sales handover?' },
      { p: 'Sales engineers are great. They also disappear after signing. Ask who the named service delivery manager will be, and ask to meet them before the contract. If you cannot get a name, the role does not exist.' },
      { h2: '7. What is your exit process?' },
      { p: 'The contract you can leave is the contract worth signing. Ask how documentation, credentials, monitoring and asset registers transfer back if you part ways. A confident MSP answers this directly. An anxious one redirects to commercial terms.' },
      { h2: 'The signal vs. the noise' },
      { p: 'The right MSP for your business is not the one with the best deck. It is the one whose answers to these questions sound like they have been answered before — because the way they run the operation has already produced them.' },
    ],
  },
  {
    slug: 'nesa-compliance-90-days',
    title: 'NESA Compliance in 90 Days: What Actually Moves the Needle',
    category: 'Cybersecurity',
    author: 'Attique Bhatti',
    date: 'Apr 24, 2026',
    readTime: '11 min',
    excerpt: 'You have an IAS audit in three months and gaps you did not know existed. Here is what to prioritise — and what to defer.',
    img: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3',
    body: [
      { h2: 'The 90-day NESA problem' },
      { p: 'Most NESA conversations start with an audit notice and a calendar that no longer has slack in it. The internal team has 90 days to close gaps that built up over years. The right question is not "how do we comply" — it is "what is the smallest amount of work that gets us to a defensible posture in time."' },
      { h2: 'Phase 1 — Weeks 1 to 2: gap assessment, no theatre' },
      { p: 'Map your current controls to the IAS framework honestly. Score every domain red, amber or green. Resist the temptation to colour-grade yourself green where you are amber. The auditor will not.' },
      { p: 'Output of this phase: a one-page gap heatmap, a prioritised remediation list with effort estimates, and a named owner for each control.' },
      { h2: 'Phase 2 — Weeks 3 to 8: close the structural gaps' },
      { p: 'Three areas almost always need work in a first NESA cycle. They are the ones we recommend tackling first because they take time and cannot be faked: asset and vendor inventories, privileged access controls, and tested business continuity plans.' },
      { p: 'Asset inventory: an actual inventory, not the spreadsheet from 2022. Vendors with access to your environment count. Privileged access: vault the credentials, enable session recording, restrict standing access. Business continuity: a tabletop exercise with the actual incident response team, not a plan in SharePoint that no-one has opened.' },
      { h2: 'Phase 3 — Weeks 9 to 11: control evidence and documentation' },
      { p: 'The auditor will spend most of their time asking for evidence. Pre-build the evidence packs — control narratives, configuration screenshots, log samples, exception registers. Run a mock audit internally before the real one. The mock audit will find at least three things you missed.' },
      { h2: 'Phase 4 — Week 12: rehearsal and audit' },
      { p: 'Final week is rehearsal. The team that will sit in the audit room should know the control narratives without reading from notes. Auditors respect confidence and specificity. They mark down ambiguity.' },
      { h2: 'What to defer' },
      { p: 'Aspirational controls — automation, advanced threat hunting, fully integrated GRC platforms — do not move the needle in a 90-day window. They are the right work for the next cycle, not this one. Defer them.' },
      { p: 'The version of this story where you are not panicking starts twelve months earlier. If that is your timeline, that is a different article. If you have 90 days, focus on the structural three and stop.' },
    ],
  },
  {
    slug: 'event-wifi-pricing-reality',
    title: 'Event WiFi That Does Not Crash: A Pricing & Planning Reality Check',
    category: 'Event IT',
    author: 'Rahul Kapoor',
    date: 'Apr 17, 2026',
    readTime: '8 min',
    excerpt: 'Why a quote for "event WiFi" can vary 10× between vendors — and what an honest scope conversation actually looks like.',
    img: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30',
    body: [
      { h2: 'Why quotes vary 10×' },
      { p: 'One vendor quotes AED 25,000. Another quotes AED 250,000. Both are pitching "event WiFi" for the same venue. The gap is not greed — it is scope. Most cheap quotes assume you do not need redundancy, do not need on-site engineers, and do not really care if the network drops during the keynote. Most expensive quotes assume you do.' },
      { h2: 'The real cost drivers' },
      { p: 'Three things move the price more than anything else: concurrent user density, redundancy level, and on-site engineering hours.' },
      { p: 'Concurrent users: a 500-person conference with corporate-grade WiFi is not the same as a 5,000-person event where every attendee is streaming. The latter needs three to five times more access points per square metre.' },
      { p: 'Redundancy: single uplink, dual uplink, or fully diverse path? Single APs or paired redundant pairs? Hot-swap controllers or single controller? Each step roughly doubles the kit cost.' },
      { p: 'On-site engineers: a single engineer for setup-only is cheap. A tiered on-site team during the event is not. If your event runs ten hours per day for three days, expect 60+ engineer-hours just on-site, before remote NOC support.' },
      { h2: 'What an honest scope conversation looks like' },
      { p: 'It starts with how many people, doing what, for how long. Then: what is the cost of a 30-minute network outage during the event? That number determines redundancy level. Then: when does the venue open for setup, when must the event be live? That determines team size and shift count.' },
      { h2: 'Where vendors cut corners' },
      { p: 'Predictive RF design skipped. Single-radio APs in a venue that needs dual-radio. No spare controller. Bandwidth contracted on a residential-grade circuit. One engineer running three venues at once. Each of these saves money up front and creates the failure that ruins the event.' },
      { h2: 'A reasonable ask' },
      { p: 'When you receive a quote, ask three things: how many APs and what model, what is the redundancy at the controller and uplink, and how many engineer-hours are budgeted. If a vendor cannot answer those quickly, the quote is built on assumptions you have not seen.' },
    ],
  },
  {
    slug: 'ipad-kiosk-deployment-playbook',
    title: 'iPad Kiosk Deployments: The Configuration Playbook',
    category: 'Rentals',
    author: 'Sarah Chen',
    date: 'Apr 09, 2026',
    readTime: '7 min',
    excerpt: 'Single-app kiosks, MDM enrolment, lockdown profiles and what to set up before delivery so day-of-event runs cleanly.',
    img: 'https://images.unsplash.com/photo-1561154464-82e9adf32764',
    body: [
      { h2: 'Why kiosks fail on day one' },
      { p: 'Most iPad kiosk failures at events are not hardware failures. They are configuration failures. An attendee finds the home button. An admin password is the default. An app crashes and there is no kiosk-mode auto-restart. The fixes are simple — but they have to happen before delivery, not at the registration desk on day one.' },
      { h2: 'The pre-delivery checklist' },
      { p: 'Single App Mode enabled via Apple Configurator or MDM. Guided Access as backup if the deployment uses unmanaged devices. Auto-lock disabled or set to "Never". Notifications disabled — including from the kiosk app itself. Screen Time and Restrictions configured so the home button, control centre, and side switches do nothing.' },
      { p: 'Network: pre-configured WiFi profile with the event SSID and password, plus a fallback SSID. Cellular if the device supports it, with a SIM that has data — not just emergency calling.' },
      { h2: 'MDM enrolment' },
      { p: 'For more than five devices, MDM is mandatory. Jamf, Microsoft Intune, Mosyle and Kandji all do the job. The MDM should enforce the configuration, push the kiosk app, and provide remote wipe and lock. Without MDM you are configuring each device by hand — and missing one means it ships with the wrong build.' },
      { h2: 'Power and physical setup' },
      { p: 'Battery life matters more than people think. An iPad in always-on kiosk mode lasts four to six hours. For a ten-hour event, you need either always-plugged kiosks or a swap protocol with a charging station. Decide before the order ships.' },
      { p: 'Cases: locked stands prevent walking. Tethered cables prevent the iPad from leaving. Both pay for themselves the first time a guest "borrows" a device for a photo.' },
      { h2: 'The day-of failure mode you cannot test' },
      { p: 'One iPad locks up. The kiosk app crashes. The screen is white. The attendant cannot fix it. Your protocol should be: swap the device, take the broken one offline, debug later. Have spare devices on site. Always. We bring 10% spares as standard for events under 50 units, 5% above that.' },
    ],
  },
  {
    slug: 'aws-vs-azure-uae-enterprises',
    title: 'AWS vs Azure for UAE Enterprises: The Honest Comparison',
    category: 'Managed IT',
    author: 'Attique Bhatti',
    date: 'Mar 31, 2026',
    readTime: '12 min',
    excerpt: 'Both have UAE regions. Both have enterprise discounts. The decision usually comes down to four factors — and price is not one of them.',
    img: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa',
    body: [
      { h2: 'The honest framing' },
      { p: 'AWS and Azure are not the same product. They are also not as different as their sales teams will tell you. For most UAE enterprises, the right answer depends on four factors: existing identity stack, regulatory data residency, application portfolio, and the team you already employ.' },
      { h2: 'Factor 1 — Identity gravity' },
      { p: 'If your organisation runs Microsoft 365 and Entra ID, Azure has gravity. Conditional Access, Privileged Identity Management and single-sign-on integration are deeper out of the box. You can do all of this against AWS too — it just takes more configuration and more brittle glue.' },
      { p: 'If your identity is Okta or Google Workspace, the gravity is neutral.' },
      { h2: 'Factor 2 — Data residency and compliance' },
      { p: 'Both providers operate UAE-resident regions. AWS Middle East (UAE) opened earlier and has broader service coverage. Azure UAE North and Central regions cover the high-value services and have caught up rapidly. For most workloads either is fine; for some regulated services, only one of the two will have the specific service available in-region.' },
      { p: 'Check the service availability map before assuming. Do not assume.' },
      { h2: 'Factor 3 — Application portfolio' },
      { p: 'Greenfield containerised workloads run well on either. Lift-and-shift Windows estates with SQL Server, .NET and Exchange typically run cheaper and easier on Azure because the licensing economics favour it. Linux-heavy, open-source-heavy estates often feel more at home on AWS.' },
      { h2: 'Factor 4 — The team you already employ' },
      { p: 'This is the factor nobody talks about and the one that determines success. A team with three AWS certifications and zero Azure certifications will build a better AWS environment than an Azure environment, even if Azure was technically the better choice. Retraining takes 12 to 18 months. Plan accordingly.' },
      { h2: 'What the price difference really looks like' },
      { p: 'Sticker prices are within 5 to 10 percent of each other for equivalent workloads. Reserved instance and savings plan discounts are similar. The real cost variance comes from how well the team operates the platform — right-sizing, shutdown schedules, storage tiers, network egress. That variance can be 30 to 40 percent. The platform is the smaller lever.' },
      { h2: 'The boring conclusion' },
      { p: 'Pick the platform that fits your identity stack, your team, and your regulatory footprint. Pick the one you can operate well, not the one with the better launch announcement.' },
    ],
  },
]

export const getArticle = (slug) => articles.find(a => a.slug === slug) || null
export const getAllArticleSlugs = () => articles.map(a => a.slug)
