export const articles = [
  { slug: 'zero-trust-practical-guide', title: 'Zero Trust in 2026: A Practical Enterprise Roadmap', category: 'Cybersecurity', author: 'Attique Bhatti', date: 'Jun 12, 2026', readTime: '12 min', excerpt: 'What Zero Trust actually means in 2026 — and a 6-step roadmap you can start this quarter.', img: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5', body: [
    { h2: 'What Zero Trust actually means' },
    { p: 'Zero Trust is an architecture, not a product. It is a shift from perimeter-based trust to identity-centric, continuously verified access decisions. In 2026, the mature form of Zero Trust combines strong identity (MFA, conditional access, device posture), micro-segmentation (ZTNA, ZTWA), and continuous verification.' },
    { h2: 'The 6-step practical roadmap' },
    { p: 'Start with a CISA Zero Trust Maturity Model (ZTMM) scoring across five pillars: Identity, Device, Network, Application Workload and Data. Pick one pillar and one use-case that drives measurable value in 90 days — typically ZTNA for remote access or Conditional Access for identity. Then scale outward.' },
    { h2: 'Common pitfalls' },
    { p: 'The #1 mistake is treating Zero Trust as a vendor bake-off. Vendors matter, but architecture matters more. The second mistake is scope creep — trying to boil the ocean kills program momentum. Ship a beachhead use-case, measure outcomes, then scale.' },
  ] },
  { slug: 'stadium-wifi-72-hours', title: 'How We Powered a 50,000-Seat Stadium Network in 72 Hours', category: 'Event IT', author: 'Rahul Kapoor', date: 'May 28, 2026', readTime: '9 min', excerpt: 'Inside the planning, kit list and on-site playbook that delivered event WiFi for one of the region’s biggest sporting events.', img: 'https://images.unsplash.com/photo-1548092372-0d1bd40894a3', body: [
    { h2: 'The brief' },
    { p: 'A major sporting event. 72 hours from venue handover to kickoff. 50,000 fans, 2,000 press and production, plus a broadcast LAN. Our team had done this before — but never this fast.' },
    { h2: 'The kit' },
    { p: '220 HPE Aruba AP-635 WiFi 6E access points, 48 Ubiquiti PtP links, 12 core switches, a full temporary NOC in a 12U portable rack, and two 10 Gbps microwave uplinks to the broadcast compound.' },
    { h2: 'What went right' },
    { p: 'Predictive RF modelling (Ekahau). Pre-staged, pre-tested gear. A playbook from 30+ prior events. 18 engineers on site in shifts. Zero P1 incidents during the event.' },
  ] },
  { slug: 'finops-azure-cut-spend', title: 'FinOps for Mid-Market: Cutting Azure Spend by 34%', category: 'Managed IT', author: 'Sarah Chen', date: 'May 15, 2026', readTime: '11 min', excerpt: 'The FinOps playbook we ran with a mid-market SaaS client that delivered 34% Azure savings in 90 days.', img: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b', body: [{ p: 'Most cloud overspend is structural, not behavioural. Fix the structure first — right-sizing, Reserved Instances, and shutdown schedules deliver 70% of the gains with 30% of the effort.' }] },
  { slug: 'sase-vendor-evaluation', title: 'Evaluating SASE Vendors in 2026: A Practical Framework', category: 'Cybersecurity', author: 'Attique Bhatti', date: 'May 08, 2026', readTime: '14 min', excerpt: 'A vendor-neutral framework for choosing between Palo Alto, Zscaler, Netskope and Cisco SASE.', img: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3', body: [{ p: 'Start with integrations and starting point, not feature matrices. Feature parity is closer than anyone admits.' }] },
  { slug: 'wifi-7-real-world', title: 'WiFi 7 in the Real World: What’s Actually Different', category: 'Networking', author: 'Rahul Kapoor', date: 'Apr 28, 2026', readTime: '7 min', excerpt: 'We’ve deployed WiFi 7 in four venues this year. Here’s what’s genuinely different and what isn’t.', img: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f', body: [{ p: 'MLO (Multi-Link Operation) is the real story. The raw throughput numbers are less interesting than the latency behaviour.' }] },
  { slug: 'laptop-rental-vs-buy', title: 'Rent or Buy: The Real Math on Enterprise Laptops', category: 'Rentals', author: 'Sarah Chen', date: 'Apr 20, 2026', readTime: '6 min', excerpt: 'We ran the numbers across 20 client scenarios. When does renting actually beat buying?', img: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853', body: [{ p: 'For temporary projects under 18 months, rental wins consistently. Above 24 months, purchase with a 3-year refresh wins.' }] },
  { slug: 'elv-converged-security', title: 'Converged Security: Why ELV and Cyber Should Be One Team', category: 'Cybersecurity', author: 'Attique Bhatti', date: 'Apr 12, 2026', readTime: '10 min', excerpt: 'Your CCTV network is an IoT estate. Treat it accordingly — or expect to be the next breach story.', img: 'https://images.unsplash.com/photo-1557804506-669a67965ba0', body: [{ p: 'In most enterprises, the CCTV VLAN is the soft underbelly. Attackers know. Security teams rarely do.' }] },
  { slug: 'ipcare-nba-toronto', title: 'Case Study: NBA Global Games in Toronto', category: 'News', author: 'IP Care Team', date: 'Apr 02, 2026', readTime: '8 min', excerpt: 'Behind the scenes at the Scotiabank Arena: the network refresh that powered a global sporting event.', img: 'https://images.unsplash.com/photo-1563841930606-67e2bce48b78', body: [{ p: 'Over 20,000 fans per night. Live broadcast to 150+ countries. Zero network incidents across five days.' }] },
  { slug: 'xsiam-vs-legacy-siem', title: 'XSIAM vs. Legacy SIEM: When the Migration Makes Sense', category: 'Cybersecurity', author: 'Attique Bhatti', date: 'Mar 25, 2026', readTime: '13 min', excerpt: 'We’ve migrated three enterprises from Splunk to XSIAM this year. Here’s the decision framework.', img: 'https://images.unsplash.com/photo-1504384764586-bb4cdc1707b0', body: [{ p: 'The honest answer: it depends. But the dependencies are fewer than you’d think.' }] },
]

export const getArticle = (slug) => articles.find(a => a.slug === slug) || null
export const getAllArticleSlugs = () => articles.map(a => a.slug)
