// Industry vertical pages — Healthcare, Banking, Government.
// Each industry has a self-contained narrative covering the regulatory
// landscape, sector-specific delivery scope, proof and FAQs.

export const industries = {
  'healthcare': {
    slug: 'healthcare',
    name: 'Healthcare IT',
    icon: 'Activity',
    keyword: 'Healthcare IT Services UAE',
    title: 'Healthcare IT UAE — Hospital, Clinic & HIE Integration | IP Care Technologies',
    metaDescription: 'Healthcare IT across the UAE — aligned to UAE healthcare data regulations, national HIE integration, medical device security and 24/7 clinical support.',
    h1: 'Healthcare IT Services in the UAE',
    hero: 'Hospital and clinic IT that does not fail during a shift — aligned to UAE healthcare data regulations, integrated with national health information exchanges, with 24/7 operational support that clinical teams can actually call.',
    overview: [
      'Healthcare IT in the UAE has a specific operational character that does not transfer cleanly from generic enterprise IT. Clinical systems run 24/7 and a five-minute outage during a busy shift is a different problem from a five-minute outage in a back-office environment. Patient data sits under federal protection rules and the relevant emirate-level health authorities apply their own classification, retention and integration requirements on top. Medical devices are increasingly networked, and that network is increasingly part of the threat surface. None of these dimensions are optional.',
      'IP Care delivers healthcare IT across the UAE — licensed hospitals and clinics in Abu Dhabi, licensed practices in Dubai, federal and military healthcare facilities, primary care chains, specialty clinics and the broader healthcare ecosystem. This page covers what we deliver in this sector, the regulatory framework that shapes the work, and why healthcare-licensed facilities engage us when they outgrow generic IT support.',
      '— The regulatory framework that actually applies —',
      'Three layers, in order of precedence.',
      'Federal. UAE Federal Law No. 2 of 2019 on the use of Information and Communication Technology in Health Fields covers electronic health records, patient data residency, consent and licensing of health IT systems nationally. The federal Personal Data Protection Law (PDPL, Decree-Law No. 45 of 2021) adds the general data protection layer. The UAE Cyber Security Council framework (formerly NESA, UAE Information Assurance Standards) applies to healthcare facilities operating at the critical-sector scale.',
      'Emirate authority. The Abu Dhabi health authority sets clinical standards, accredits facilities and runs the unified health information exchange that every licensed facility in the emirate connects to. The Dubai health authority sets clinical standards and runs the Dubai HIE equivalent. Riayati is the federal HIE that connects across the country.',
      'Sector-specific overlays. Joint Commission International (JCI) accreditation is the operational gold standard most major UAE hospitals pursue and the IT controls that JCI surveys are non-trivial. ISO 27001 and HIMSS EMRAM stage assessments add another layer for facilities pursuing those certifications.',
      '— What healthcare facilities actually need from IT —',
      'Four categories cover the bulk of what we deliver.',
      'Clinical system support that runs on a clinical clock. Hospital information systems, electronic medical records (EMR), lab and imaging systems, pharmacy management, OR and ICU systems — every category has its own uptime expectations, its own change-window discipline and its own integration footprint. We staff 24/7 support with engineers who understand that a Friday-night incident at a busy ER is not the same urgency as a Friday-night incident at a corporate office. The SLA on paper is identical. The operational tempo around it is not.',
      'HIE integration. National health information exchange integration is mandatory for licensed facilities and the integration is not a one-time project. New systems, EMR upgrades, lab integrations and ancillary systems all need to maintain the HIE handshake. We run continuous HIE integration as a service for several Abu Dhabi and Dubai facilities, including the mandatory ADT, lab result, radiology report and pharmacy event flows.',
      'Medical device security. The medical-device estate in a modern hospital is materially larger than the IT estate. Infusion pumps, monitors, imaging modalities, surgical robotics, lab analysers — all networked, most running operating systems with limited patching options, almost all communicating with clinical workflows. Securing this estate is not a generic endpoint problem. The work is medical-device-specific network segmentation, asset inventory at the device level, vendor remote-access controls and active monitoring of clinical VLAN traffic.',
      'Compliance and audit readiness. JCI surveys, emirate health authority audits, federal PDPL audits and ISO 27001 surveillance audits all touch healthcare IT controls. The evidence work — patient data access logs, change-management approvals, BCP exercise records, medical device inventory accuracy — is where most facilities lose marks at audit time. We build the evidence repository as part of the engagement so the next audit is the routine one.',
      '— How we work in this sector —',
      'Our healthcare practice operates from our Abu Dhabi headquarters with on-site engineering and 24/7 NOC coverage. Most healthcare engagements start with a focused assessment — current systems, current pain points, current audit readiness — and convert into a managed services engagement covering 24/7 operations, HIE integration maintenance and compliance support.',
      'We are vendor-agnostic on hospital information system and EMR platforms. We work with Cerner, Epic, Medsphere, InterSystems TrakCare, the regional Avicenna and Medweb stacks, and the smaller specialty platforms that single-site clinics often run. Vendor relationships matter for support escalation, but we do not push a specific platform.',
      'We hire engineers with healthcare experience for the on-site clinical roles. A generic IT engineer learning the rhythm of a busy clinical floor is a different proposition from an engineer who has worked in healthcare before. The first six months for a generic hire are paid in clinical-floor incidents nobody wants to absorb.',
      '— Why healthcare facilities engage us —',
      'Four reasons come up consistently in renewal conversations. UAE healthcare regulatory fluency — emirate health authority requirements, national HIE integration, federal PDPL and the federal Health ICT Law are part of the standard operating context. Twenty years in UAE security and infrastructure — most healthcare incidents are preventable and the institutional history with the relevant vendors and authorities compounds. Operational discipline — same engineers across the shift pattern, same runbook, same change-window discipline, with the clinical-time awareness that clinical environments need. Cross-portfolio depth — our event-IT SOC capability and our enterprise cybersecurity practice underpin the healthcare engagement when the threat profile justifies it.',
    ],
    regulatoryFramework: [
      { name: 'UAE Federal Law No. 2 of 2019', scope: 'Use of ICT in Health Fields — patient data residency, EHR, consent.' },
      { name: 'Federal PDPL (Decree-Law No. 45 of 2021)', scope: 'Personal data protection — applies on top of sector regulations.' },
      { name: 'Abu Dhabi health authority standards', scope: 'Clinical standards, facility accreditation, HIE integration mandate.' },
      { name: 'Dubai health authority standards', scope: 'Clinical standards, facility licensing, HIE integration mandate.' },
      { name: 'Abu Dhabi HIE', scope: 'Unified health information exchange — mandatory for licensed facilities.' },
      { name: 'Dubai HIE', scope: 'Dubai health information exchange.' },
      { name: 'NESA / UAE IAS', scope: 'Cyber Security Council framework — applies to critical-sector healthcare entities.' },
      { name: 'JCI accreditation', scope: 'Operational gold standard for major UAE hospitals — surveys IT controls.' },
    ],
    serviceHooks: [
      { title: '24/7 Managed IT for Hospitals & Clinics', desc: 'Clinical-clock support with shift-aware on-site and remote NOC, change-window discipline and SLA tiers for clinical, ancillary and back-office.', href: '/services/managed-it', icon: 'Server' },
      { title: 'National HIE Integration', desc: 'Continuous integration with national health information exchanges in Abu Dhabi and Dubai. ADT, lab, radiology and pharmacy event flows.', href: '/services/managed-it/network-management', icon: 'Network' },
      { title: 'Medical Device Security', desc: 'Clinical VLAN segmentation, device asset inventory, vendor remote-access controls and active OT-style monitoring.', href: '/services/cybersecurity', icon: 'ShieldCheck' },
      { title: 'Cybersecurity for Healthcare', desc: 'PDPL alignment, NESA controls where in scope, identity-first defence on Microsoft Entra ID, email security for clinical users.', href: '/services/cybersecurity/abu-dhabi', icon: 'Lock' },
      { title: 'Cloud Services with UAE Residency', desc: 'Azure UAE North / AWS Middle East UAE landing zones aligned with patient-data residency rules.', href: '/services/cloud/abu-dhabi', icon: 'Cloud' },
      { title: 'CCTV & ELV for Healthcare Facilities', desc: 'ADMCC-certified (Abu Dhabi) CCTV and access control for clinical and back-of-house areas.', href: '/services/elv', icon: 'Video' },
    ],
    proof: [
      { stat: '24/7', label: 'Clinical-clock operations' },
      { stat: 'National HIE', label: 'HIE integration as a service' },
      { stat: '20+ years', label: 'UAE healthcare delivery history' },
      { stat: 'JCI-aware', label: 'Audit-ready IT controls and evidence' },
    ],
    faqs: [
      { q: 'Do you handle national HIE integration?', a: 'Yes. Health information exchange integration for Abu Dhabi and Dubai is a continuous engagement, not a one-time project. We maintain the ADT, lab result, radiology report and pharmacy event flows for several UAE facilities and treat the HIE handshake as a standing service alongside system upgrades and ancillary integrations.' },
      { q: 'What clinical systems do you support?', a: 'Vendor-agnostic across hospital information systems and EMRs — Cerner, Epic, Medsphere, InterSystems TrakCare, Avicenna, Medweb and the smaller specialty platforms used by single-site clinics. We pick the support stance based on what the facility runs, not on what we want to sell.' },
      { q: 'How do you handle medical device security?', a: 'As a distinct workstream from general endpoint security. Clinical VLAN segmentation, device-level asset inventory, vendor remote-access controls and active monitoring of clinical network traffic. The medical-device estate in a modern hospital is materially larger than the IT estate, and the threat profile is different. Generic endpoint security does not cover it.' },
      { q: 'Are you JCI-aware?', a: 'Yes. We build the IT control environment so that JCI survey requirements (access logs, change management, BCP exercises, medical device inventory) are evidenced as part of the operating rhythm — not gathered at the last minute before a survey.' },
      { q: 'How does the federal PDPL apply to healthcare data?', a: 'PDPL applies on top of the sector-specific health data rules. Patient data is sensitive personal data under PDPL with the standard residency, consent and access-control requirements. We map data classes against PDPL requirements as part of the cloud and IT design work, and configure the operating environment to enforce the residency and access policies automatically where possible.' },
      { q: 'Where is your support team based?', a: 'Our healthcare practice operates from our Abu Dhabi headquarters with on-site engineering at client sites and 24/7 NOC coverage. Toronto provides backstop coverage for our Canadian healthcare clients.' },
    ],
  },

  'banking': {
    slug: 'banking',
    name: 'Banking & Financial Services IT',
    icon: 'Building2',
    keyword: 'Banking IT Services UAE',
    title: 'Banking IT Services UAE — Compliance & SOC | IP Care',
    metaDescription: 'Banking IT across UAE — compliance-ready cloud and SOC, payment systems integration and FATF-aligned security for banks and financial services firms.',
    h1: 'Banking & Financial Services IT in the UAE',
    hero: 'Compliance-ready cloud and SOC aligned to your banking regulator\'s requirements — payment systems integration and a managed SOC that actually catches threats during business hours.',
    overview: [
      'Banking IT in the UAE runs against the most demanding regulatory envelope of any commercial sector. The applicable banking regulations prescribe the security control set for licensed banks, while firms based in the DIFC and ADGM operate under the relevant financial-services regulator\'s framework. FATF-aligned anti-money-laundering requirements apply at the operational level. Payment system rules from UAE Direct, UAEFTS, AANI and the international card schemes apply at the technical level. None of these are optional. All of them get audited.',
      'IP Care delivers banking and financial services IT across UAE-licensed banks, DIFC-based firms, ADGM-based firms, exchange houses, payment-services providers and the broader regulated financial services ecosystem. This page covers what we deliver in this sector, the regulatory layer that shapes the work, and why financial services firms engage us when generic IT support is not enough.',
      '— The regulatory framework that actually applies —',
      'Three layers, with material overlap.',
      'Your banking regulator. The applicable banking regulations form the baseline information security framework for licensed banks and the broader payment-services ecosystem. They set the control framework, the audit cycle, the incident reporting timelines and the third-party risk management expectations. Compliance is the licence condition, not a goal.',
      'Free-zone financial regulations. Firms based in the DIFC and ADGM operate under the relevant financial-services regulator\'s cyber rules. The frameworks differ in detail but the operational content overlaps materially with the applicable framework for banks — same risk discipline, same incident response posture, same third-party risk management.',
      'Federal and international overlays. The federal PDPL applies to customer data. The UAE Cyber Security Council framework (formerly NESA, UAE IAS) applies to banks at the critical-sector scale. FATF-aligned AML, sanctions screening against UN/UK/US OFAC lists, and PCI-DSS for card environments all add their own technical control layers.',
      '— What financial services firms actually need from IT —',
      'Four categories cover most of what we deliver.',
      'Managed SOC for banking. A compliance-ready security operations capability is a foundational requirement — continuous monitoring, threat detection, incident response, regulator reporting. Our managed SOC runs Palo Alto Cortex XSIAM, Microsoft Sentinel or comparable SIEM, with banking-tuned use cases and incident reporting templates aligned to your regulator\'s timing requirements. The same SOC capability underpins our event-IT engagements (UFC, NBA, Coldplay) which gives the analyst team threat-response depth that pure enterprise-only SOCs rarely match.',
      'Cloud for banking compliance. Banking cloud workloads carry strict residency, audit-logging and segmentation requirements. We build compliance-ready landing zones on Azure UAE North or AWS Middle East UAE — identity federation, classification-driven residency enforcement, audit-logging to your banking regulator\'s standards, payment systems isolation and the third-party cloud-provider security obligations integrated into the design from day one.',
      'Payment systems and resilience. UAE Direct, UAEFTS, AANI instant payments and the international card scheme connectivity all sit on segmented, hardened network infrastructure with the resilience and DR characteristics the payment systems demand. We build and operate this infrastructure with the segmentation and audit-trail discipline that payment system audits expect.',
      'Identity, sanctions and KYC infrastructure. Microsoft Entra ID-based identity for the workforce, integration with KYC and sanctions screening platforms (Refinitiv World-Check, Dow Jones Risk and Compliance, the regional alternatives), PIM and conditional access policies that pass regulator scrutiny. The IT layer underneath the AML and sanctions workflows is where most banks find compliance gaps at audit time.',
      '— How we work in this sector —',
      'Our banking practice operates from our Abu Dhabi headquarters with the SOC physically based in the same building. Engagements typically start with a focused assessment against the applicable regulatory framework — the applicable banking regulations for banks, and the relevant financial-services regulator\'s framework for DIFC and ADGM-based firms — and convert into a managed services engagement covering SOC operations, ongoing compliance and the cloud and identity work that underpins the security posture.',
      'We treat the regulator relationship as part of the engagement. Incident reporting follows the timing your regulator expects, with the evidence pack and the post-incident analysis written for the regulator audience, not just internal stakeholders. Banks under regulatory enforcement attention know how much this matters. Banks that have not yet been there sometimes underestimate it.',
      'We are not the cheapest banking IT vendor in the region. We are the one that operates at the regulatory standard from day one, not retrofits to it. Those two statements are connected.',
      '— Why financial services firms engage us —',
      'Four reasons come up consistently. UAE regulatory fluency at the operational level — your banking regulator\'s requirements, PDPL and the relevant sector overlays are part of the standard operating context. SOC depth tested in event-IT engagements — the same analyst team that watches an NBA Abu Dhabi broadcast watches the banking enterprise estate during business hours and after. Compliance-ready cloud landing zones as standard practice — we build to the regulation from day one, not retrofit to it. Twenty years in UAE security — most banking incidents are preventable, and the institutional history with the UAE financial regulatory environment and the relevant authorities compounds.',
    ],
    regulatoryFramework: [
      { name: 'Banking regulator framework', scope: 'Information security regulation for licensed banks and payment-services providers — the applicable banking regulations.' },
      { name: 'Free-zone financial regulations (DIFC)', scope: 'Cyber risk management framework for firms based in the DIFC — risk management, incident response, third-party risk.' },
      { name: 'Free-zone financial regulations (ADGM)', scope: 'Cyber rules for firms based in the ADGM — broadly parallel to the DIFC framework.' },
      { name: 'Federal PDPL', scope: 'Personal data protection — customer data handling, consent, residency.' },
      { name: 'NESA / UAE IAS', scope: 'Cyber Security Council framework — applies to banks at critical-sector scale.' },
      { name: 'FATF-aligned AML', scope: 'Anti-money-laundering and sanctions screening operational requirements.' },
      { name: 'PCI-DSS', scope: 'Payment card industry data security for card environments.' },
      { name: 'Payment system rules', scope: 'UAE Direct, UAEFTS, AANI and international card scheme connectivity standards.' },
    ],
    serviceHooks: [
      { title: 'Managed SOC for Banking', desc: 'XSIAM or Sentinel SIEM with banking-tuned use cases, incident reporting templates aligned to your banking regulator\'s timing, 24/7 analyst coverage.', href: '/services/cybersecurity/abu-dhabi', icon: 'ShieldCheck' },
      { title: 'Compliance-Ready Banking Cloud', desc: 'Azure UAE North or AWS Middle East UAE landing zones with residency, audit-logging, segmentation and third-party controls built in.', href: '/services/cloud/abu-dhabi', icon: 'Cloud' },
      { title: 'Identity & Access for Banking', desc: 'Microsoft Entra ID with Conditional Access, PIM, MFA and identity governance — pass regulator scrutiny at audit.', href: '/services/cybersecurity/microsoft-entra-id', icon: 'KeyRound' },
      { title: 'Endpoint & Email Security', desc: 'CrowdStrike, SentinelOne or Microsoft Defender for Endpoint plus Proofpoint or Mimecast email security for BEC and phishing.', href: '/services/cybersecurity/endpoint-protection', icon: 'Lock' },
      { title: 'NESA / UAE IAS for Banks', desc: 'For banks at critical-sector scale — gap assessment, control implementation and ongoing controls operation.', href: '/services/cybersecurity/nesa-compliance', icon: 'FileCheck' },
      { title: 'CCTV & ELV for Branches', desc: 'ADMCC-certified (Abu Dhabi) CCTV, access control and intercom for branch networks and head office.', href: '/services/elv', icon: 'Video' },
    ],
    proof: [
      { stat: '24/7', label: 'Managed SOC in Abu Dhabi' },
      { stat: 'Regulation-ready', label: 'Standard practice, not retrofit' },
      { stat: '100K+ users', label: 'Cybersecurity practice protected to date' },
      { stat: '20+ years', label: 'UAE financial services delivery history' },
    ],
    faqs: [
      { q: 'Do you build compliance-ready cloud landing zones for banking?', a: 'Yes. The applicable banking regulatory control set is integrated into the landing zone reference architecture — residency, audit-logging, segmentation, identity, third-party risk — and validated as part of the build, not retrofitted after migration. Azure UAE North is the typical primary region; AWS Middle East UAE is the alternative for AWS-anchored portfolios.' },
      { q: 'Where is your SOC located?', a: 'Our primary SOC is physically based in Abu Dhabi, with 24/7 analyst coverage. The same SOC capability that monitors the banking enterprise estate during business hours runs our event-IT engagements (UFC, NBA, Coldplay, IIFA) when those events are live. That cross-portfolio depth is unusual.' },
      { q: 'How do you handle banking regulator incident reporting?', a: 'Incident reporting timing is part of the SOC runbook. Detection and triage happen on the standard SOC clock; reporting follows your banking regulator\'s framework. The evidence pack and post-incident analysis are written for the regulator audience, not just internal stakeholders.' },
      { q: 'Do you work with DIFC and ADGM-based firms?', a: 'Yes. Cyber risk management work for firms based in the DIFC and equivalent work for firms based in the ADGM are regular parts of our scope. The two frameworks parallel each other and parallel the applicable banking regulations with material overlap, so the underlying operating model translates across the three regimes.' },
      { q: 'Can you handle PCI-DSS for card environments?', a: 'Yes. PCI-DSS environment isolation, audit logging, vulnerability management and quarterly attestation are part of the standard scope for clients with card-processing environments. The integration with the broader banking regulatory control set means a single operating model satisfies both.' },
      { q: 'Are you cheap?', a: 'No. We are not the cheapest banking IT vendor in the region and we do not pretend to be.' },
    ],
  },

  'government': {
    slug: 'government',
    name: 'Government & Federal IT',
    icon: 'Landmark',
    keyword: 'Government IT Services UAE',
    title: 'Government IT UAE — Federal-Grade Cloud, NESA, Classified Operations | IP Care',
    metaDescription: 'Government IT services for UAE federal entities, government-adjacent organisations and quasi-sovereign clients. Federal-grade Azure UAE North, NESA / UAE IAS, classification handling and federal-stakeholder integration.',
    h1: 'Government & Federal IT in the UAE',
    hero: 'Federal-grade IT delivery for UAE government entities, sovereign and quasi-sovereign organisations — Azure UAE North landing zones, NESA / UAE IAS as standard practice, classification-aware operations and the operating-procedure familiarity that comes with two decades of federal work.',
    overview: [
      'Government and federal IT in the UAE is a category of work that very few commercial vendors deliver well. The combination of classification handling, federal-stakeholder integration, sector-regulator co-ordination, personnel security clearance requirements and the operating-procedure overlay that federal entities maintain is harder than the sum of its parts. The first year of any vendor on a federal engagement is a substantial learning curve. The third year is operational.',
      'IP Care has delivered government and federal IT from our Abu Dhabi headquarters since 2003. The practice covers federal entities, government-adjacent organisations, sovereign and quasi-sovereign clients, federal energy-sector work, and the broader UAE government technology footprint. This page covers what we deliver in this sector, the regulatory and operational framework that shapes the work, and what makes federal IT in the UAE structurally different from commercial enterprise IT.',
      '— The regulatory and operational framework —',
      'Five layers interact in federal work.',
      'UAE Cyber Security Council and NESA / UAE IAS. The Cyber Security Council (the policy authority that absorbed NESA in 2020) sets national cybersecurity strategy and the UAE Information Assurance Standards apply mandatorily to federal entities and government-adjacent organisations. Compliance is not optional and is audited through the federal stakeholder system.',
      'Digital government regulation. The national telecom and digital-government regulator sets the digital government framework, the spectrum allocations and the cross-government IT standards for federal entities.',
      'Federal personnel-security requirements. The federal human resources authority runs the personnel security clearance framework for cleared roles in federal entities and the more sensitive government-adjacent organisations. Cleared roles operate against vetting, classification and access requirements that commercial roles do not encounter.',
      'Federal PDPL. The Personal Data Protection Law applies to all personal data handled by federal entities and the related government-adjacent organisations with the standard residency, consent and access-control overlay.',
      'Sector-specific overlays. The federal energy sector and its regulatory framework, federal government banking entities, federal health (federal hospitals and the Ministry of Health and Prevention), and federal defence-adjacent entities all carry additional specification overlays on top of the general federal framework.',
      '— What federal entities actually need from IT —',
      'Four categories cover most of what we deliver in this sector.',
      'Federal-grade landing zones. Azure UAE North is the federal-grade Azure region in the UAE and the typical primary region for federal entity workloads. AWS Middle East UAE is operationally available for AWS-anchored federal portfolios. Federal-grade landing zones integrate with federal directories, enforce classification-driven residency, integrate with federal-stakeholder monitoring and maintain the audit-trail evidence handling standard that federal sign-off requires. We build these landing zones to the federal reference, not to a generic commercial baseline that gets retrofitted.',
      'NESA / UAE IAS programmes. Federal entities operate against NESA / UAE IAS as a mandatory framework. The 188-control envelope across the six management domains (M1 to M6) and nine technical domains (T1 to T9), the Information Assurance Maturity Model (IAMM) self-assessment, the formal IAS audit and the ongoing controls operation are all part of the standard federal IT engagement. Our NESA practice has documented delivery history across federal, energy, banking and healthcare clients in the UAE.',
      'Classification-aware operations. Federal entities handle classified information across multiple classification levels. The IT environment supporting classified work runs at higher access-control, audit-logging, monitoring and physical-security standards than commercial work. Classified-system support, classified-print and classified-fax workflows, classified email and classified collaboration platforms all need operating teams cleared and operationally familiar with the relevant clearance regime.',
      'Federal-stakeholder integration. Federal entities operate as part of a broader federal stakeholder system — UAE Cyber Security Council reporting, national digital-government integration, federal-stakeholder dashboard reporting, inter-entity data exchange and the operating-procedure co-ordination that the federal system maintains. Building IT that integrates cleanly with this stakeholder system is what separates federal-experienced vendors from commercial-only vendors.',
      '— Smart city and digital government —',
      'Beyond the core federal IT scope, we work with the smart city and digital government programmes that have become a defining feature of UAE government technology over the past decade. TAMM (the Abu Dhabi government services platform), DubaiNow (the Dubai government services platform), UAE PASS (the federal digital identity), the Smart Dubai and Abu Dhabi Smart City initiatives and the broader digital government agenda all generate IT engagement scope at the federal and emirate-government level. The work spans cloud, identity, integration, security and the broader infrastructure operating model.',
      '— Why federal entities engage us —',
      'Five reasons come up consistently. Local headquarters and operating history — Abu Dhabi-based since 2003 with continuous federal and government-adjacent delivery throughout that period. NESA / UAE IAS depth — multi-sector practice with documented federal, energy, banking and healthcare delivery history. Classification fluency — operating teams cleared and operationally familiar with the relevant clearance regime. Cross-portfolio depth — our work on UAE Official National Day (48th and 49th editions), the federal Cyber Security Council ecosystem and the broader federal client base compounds. Vendor neutrality on advisory engagements — advisory scope structurally separate from delivery scope, which matters more in federal procurement than in commercial procurement.',
    ],
    regulatoryFramework: [
      { name: 'UAE Cyber Security Council', scope: 'National cybersecurity strategy, policy framework, federal stakeholder oversight.' },
      { name: 'NESA / UAE IAS', scope: 'Mandatory framework for federal entities — 188 controls across 15 domains.' },
      { name: 'National telecom and digital-government regulator', scope: 'Digital government framework, spectrum and cross-government IT standards.' },
      { name: 'Federal personnel-security requirements', scope: 'Federal clearance framework — vetting, classification and access requirements for cleared roles.' },
      { name: 'Federal PDPL', scope: 'Personal data handled by federal entities — residency, consent, access control.' },
      { name: 'UAE PASS', scope: 'Federal digital identity framework for citizen and resident-facing services.' },
      { name: 'Sector overlays', scope: 'Federal energy sector, federal government banking, federal health, federal defence-adjacent.' },
    ],
    serviceHooks: [
      { title: 'Federal-Grade Azure UAE North Landing Zones', desc: 'Identity federation with federal directories, classification-driven residency, federal-stakeholder monitoring integration.', href: '/services/cloud/abu-dhabi', icon: 'Cloud' },
      { title: 'NESA / UAE IAS Programmes', desc: 'Gap assessment, remediation, IAS audit preparation, ongoing controls operation across the 188-control framework.', href: '/services/cybersecurity/nesa-compliance', icon: 'FileCheck' },
      { title: 'Managed SOC for Federal', desc: 'XSIAM or Sentinel SIEM with federal-stakeholder integration, classification-aware monitoring and analyst coverage.', href: '/services/cybersecurity/abu-dhabi', icon: 'ShieldCheck' },
      { title: 'Identity & Access for Federal Entities', desc: 'Microsoft Entra ID federation with federal directories, PIM, Conditional Access and identity governance for cleared and uncleared roles.', href: '/services/cybersecurity/microsoft-entra-id', icon: 'KeyRound' },
      { title: 'IT Consulting for Federal Strategy', desc: 'Technology strategy aligned with UAE Centennial 2071, National Cybersecurity Strategy and sector digital agendas.', href: '/services/it-consulting/abu-dhabi', icon: 'Compass' },
      { title: 'ELV for Federal Premises', desc: 'ADMCC-certified CCTV, access control and ELV for federal buildings — classification-aware design and federal-stakeholder integration.', href: '/services/elv/abu-dhabi', icon: 'Building2' },
    ],
    proof: [
      { stat: '20+ years', label: 'Continuous federal delivery from Abu Dhabi' },
      { stat: 'NESA', label: 'Multi-sector federal delivery history' },
      { stat: 'UAE National Day', label: '48th & 49th edition IT delivery' },
      { stat: 'Federal-grade', label: 'Azure UAE North standard practice' },
    ],
    faqs: [
      { q: 'Do you have federal experience?', a: 'Yes. IP Care has delivered IT for federal entities and government-adjacent organisations continuously since 2003 from our Abu Dhabi headquarters. The institutional history with UAE Cyber Security Council reporting, NESA / UAE IAS audits, national digital-government integration and the broader federal stakeholder system is part of the standard operating context.' },
      { q: 'Are your engineers cleared?', a: 'For cleared roles in federal engagements, our operating teams hold the relevant clearance and the operational familiarity with the federal personnel-security requirements. We do not staff cleared roles with uncleared engineers and we do not transfer cleared engineers between unrelated engagements.' },
      { q: 'How do you handle classified work?', a: 'Classified work runs at higher access-control, audit-logging, monitoring and physical-security standards than commercial work, with cleared operating teams and the operating-procedure overlay the relevant entity maintains. The IT environment supporting classified work is purpose-built for the classification level, not adapted from a commercial baseline.' },
      { q: 'What is the typical engagement structure for a federal entity?', a: 'A focused assessment first — current state, NESA / UAE IAS posture, federal-stakeholder integration gaps. Then a phased programme covering the priority remediation and the conversion to managed services for ongoing operation. Federal engagements typically run multi-year because the operational maturity that produces clean federal stakeholder relationships compounds across years rather than months.' },
      { q: 'Do you deliver smart city and digital government work?', a: 'Yes. TAMM, DubaiNow, UAE PASS, the Smart Dubai and Abu Dhabi Smart City programmes and the broader digital government agenda all generate IT engagement scope at the federal and emirate-government level. We work across cloud, identity, integration, security and the broader infrastructure operating model.' },
      { q: 'Can you handle federal energy and federal banking work?', a: 'Yes. Federal energy-sector work with the OT security overlay, federal government banking work, and the broader sector-specific federal scope are all part of our regular delivery. The sector-specific overlay on top of the general federal framework is where the engagement complexity lives.' },
    ],
  },
}

export const getAllIndustries = () => Object.values(industries)
export const getAllIndustrySlugs = () => Object.keys(industries)
export const getIndustry = (slug) => industries[slug] || null
