const service = {
  cctv: { label: 'CCTV Systems', href: '/services/elv/cctv-systems' },
  access: { label: 'Access Control', href: '/services/elv/access-control' },
  cabling: { label: 'Structured Cabling & Fiber', href: '/services/elv/structured-cabling' },
  elv: { label: 'ELV & Physical Security', href: '/services/elv' },
  network: { label: 'Network Infrastructure', href: '/services/infrastructure' },
  managedIt: { label: 'Managed IT', href: '/services/managed-it' },
  pa: { label: 'PA Systems', href: '/services/elv/public-address-systems' },
}

const enterpriseProjects = [
  {
    name: 'Yas Driving Academy',
    slug: 'yas-driving-academy',
    type: 'Enterprise Facilities',
    industry: 'Education & Training',
    location: 'Abu Dhabi, UAE',
    year: 'Delivered',
    deliveredYear: '2025',
    services: [service.cctv, service.cabling, service.network, service.access],
    proofPoint:
      'A complete ICT and ELV build for a high-volume training facility — 63 cameras, Wi-Fi 7 coverage, a Fortinet-secured network, 12 access-controlled doors and a UPS-backed core, delivered by one accountable team.',
    metaDescription:
      'Yas Driving Academy, Abu Dhabi: 63 CCTV cameras, Wi-Fi 7, a Fortinet network, 12 access-controlled doors and UPS-backed power, delivered by IP Care.',
    challenge:
      'A high-use education and training environment needs security, connectivity and physical access working as one system — not five separate contracts that meet for the first time at commissioning.',
    scope:
      'Structured cabling and fiber backbone, a Fortinet network with Wi-Fi 7 coverage, 63-camera CCTV, Suprema access control and UPS-backed power protection.',
    outcome:
      'Every system cabled, configured, tested and handed over by one engineering team, with certified test results and manufacturer support registered from day one.',
    // At-a-glance facts rendered in the case-study hero.
    facts: [
      { label: 'Client', value: 'Yas Driving Academy' },
      { label: 'Sector', value: 'Education & Training' },
      { label: 'Location', value: 'Abu Dhabi, UAE' },
      { label: 'Delivered', value: '2025' },
      { label: 'Role', value: 'Principal ICT & ELV contractor' },
    ],
    // Headline figures — every value traced to the project BOQ.
    stats: [
      { value: '63', label: 'CCTV cameras', note: '4MP dual-light varifocal' },
      { value: '15', label: 'Wi-Fi 7 access points', note: '13 indoor, 2 outdoor' },
      { value: '240', label: 'PoE+ switch ports', note: '5 × 48-port FortiSwitch' },
      { value: '7.6 km', label: 'Cat6A cable', note: '200 terminations' },
      { value: '1,000 m', label: 'Armored fiber', note: '12-core single-mode' },
      { value: '12', label: 'Controlled doors', note: 'Licensed to 50' },
    ],
    featured: true,
    priority: 20,
    image: '/images/portfolio/yas-driving-academy/hero.webp',
    imageAlt: 'IP Care delivery at Yas Driving Academy, Abu Dhabi — YDA facility and branded vehicle',
    imageVerified: true,
    imageCaption: 'IP Care on-site delivery at Yas Driving Academy',
    clientLogo: '/images/portfolio/yas-driving-academy/client-logo.webp',
    relatedHref: '/services/elv',
    // Real on-site project photos from IP Care's YDA delivery, grouped by scope of work.
    // See docs/superpowers/specs/2026-07-21-yas-driving-academy-video-case-study-design.md
    caseStudy: true,
    workBreakdown: [
      {
        scope: 'CCTV Systems',
        icon: 'Cctv',
        blurb:
          'Sixty-three Hikvision dual-light cameras installed and aligned across the facility — dome coverage over interiors and circulation, bullet cameras on external approaches and the training yard, each on its own certified Cat6 run.',
        specs: [
          '51 × 4MP dual-light varifocal dome cameras (2.8–12 mm)',
          '12 × 4MP dual-light varifocal bullet cameras (2.8–12 mm)',
          '63 dedicated Cat6 camera runs, terminated and tested',
          'Camera positioning, focus and field-of-view configured on site',
        ],
        photos: [
          { src: '/images/portfolio/yas-driving-academy/work-1.webp', alt: 'IP Care technician installing an external CCTV camera at Yas Driving Academy' },
        ],
      },
      {
        scope: 'Structured Cabling & Fiber',
        icon: 'Cable',
        blurb:
          'The physical layer everything else depends on: Cat6A throughout, a 12-core armored single-mode backbone between rooms, and every link Fluke-certified and OTDR-tested before a single system was energized.',
        specs: [
          '7.6 km Cat6A U/UTP 23AWG, 200 keystone terminations',
          '1,000 m 12-core armored single-mode fiber backbone',
          '1 × 42U main rack + 3 × 12U satellite racks, power strips fitted',
          '7 × 24-port patch panels, 4 × fiber patch panels, 96 LC pigtails spliced',
          '100 floor boxes and shutters, 20 faceplates',
          'Full labeling, Fluke channel certification and OTDR test reports',
        ],
        photos: [
          { src: '/images/portfolio/yas-driving-academy/work-5.webp', alt: 'IP Care engineer Fluke-testing terminated Cat6 links at the patch panels in the Yas Driving Academy comms rack' },
          { src: '/images/portfolio/yas-driving-academy/work-2.webp', alt: 'IP Care team installing overhead cabling and containment at Yas Driving Academy' },
          { src: '/images/portfolio/yas-driving-academy/work-3.webp', alt: 'IP Care technicians terminating floor data cabling at Yas Driving Academy' },
        ],
      },
      {
        scope: 'Network & Wi-Fi 7',
        icon: 'Network',
        blurb:
          'A Fortinet security fabric from the edge in — firewall supplied and configured, FortiSwitch access layer on 10G fiber uplinks, and Wi-Fi 7 coverage engineered for a facility where classrooms, offices and an outdoor training yard all need to stay connected.',
        specs: [
          'FortiGate firewall supplied, installed and configured',
          '5 × FortiSwitch-148F-FPOE — 240 PoE+ ports, 740 W PoE budget each',
          '13 × FortiAP-441K indoor Wi-Fi 7 tri-band access points',
          '2 × FortiAP-432G outdoor access points for external coverage',
          '12 × 10GE SFP+ long-range modules for the fiber uplinks',
          'Switch, AP and firewall configuration under central FortiGate control',
        ],
      },
      {
        scope: 'Access Control',
        icon: 'Fingerprint',
        blurb:
          'Twelve controlled doors from reader to lock to software — Suprema IP67 dual-frequency readers, magnetic locks with compliant emergency release, all managed under one BioStar 2 platform with headroom to grow to fifty doors.',
        specs: [
          '12 × Suprema XPass XP2-MDPB dual-RFID mullion readers (IP67, IK08, NFC/BLE)',
          '13 × 600 lbs magnetic locks',
          '12 × no-touch exit buttons and 12 × emergency break-glass units',
          'BioStar 2 Standard licence — 50-door capacity',
          'Dedicated cabling and fixing for every reader, lock and release device',
        ],
        photos: [
          { src: '/images/portfolio/yas-driving-academy/work-4.webp', alt: 'IP Care engineers routing cabling at an access-controlled entrance at Yas Driving Academy' },
        ],
      },
      {
        scope: 'Power Protection',
        icon: 'BatteryCharging',
        blurb:
          'Security and network hardware are only as available as the power behind them. Eaton UPS protection was fitted at the core so cameras, switches and door controllers ride through a mains event rather than rebooting into one.',
        specs: [
          '1 × Eaton 9SX 6000i RT3U online UPS protecting the main rack',
          '1 × Eaton 5PX 1000VA RT2U UPS for satellite equipment',
          'Rack-mounted, integrated with the 42U core and distribution',
        ],
      },
    ],
    // Full equipment schedule from the project BOQ — shown as the technical summary table.
    techStack: [
      {
        system: 'Structured Cabling',
        vendor: 'D-Link / D-Connect',
        items: [
          { item: 'Cat6A 23AWG U/UTP cable (305 m box)', qty: '25 boxes' },
          { item: '42U rack 800 × 1000 mm with power strip', qty: '1' },
          { item: '12U rack 600 × 600 mm with power strip', qty: '3' },
          { item: 'Cat6A UTP keystone jacks', qty: '200' },
          { item: '24-port unloaded patch panel, 1U + cable manager', qty: '7' },
          { item: 'Floor shutters', qty: '100' },
          { item: 'Cat6A patch cords, 1 m', qty: '120' },
          { item: '12-core OS1/OS2 armored single-mode fiber', qty: '1,000 m' },
          { item: '1U 24-port fiber patch panel with splice tray', qty: '4' },
          { item: 'Single-mode duplex LC adaptors', qty: '48' },
          { item: 'LC/UPC single-mode pigtails', qty: '96' },
        ],
      },
      {
        system: 'Network & Wireless',
        vendor: 'Fortinet',
        items: [
          { item: 'FortiGate firewall — supplied and configured', qty: '1' },
          { item: 'FortiSwitch-148F-FPOE 48-port PoE+ switch', qty: '5' },
          { item: 'FortiAP-441K indoor Wi-Fi 7 access point', qty: '13' },
          { item: 'FortiAP-432G outdoor access point', qty: '2' },
          { item: '10GE SFP+ long-range transceiver (10 km, LC, SMF)', qty: '12' },
          { item: 'FortiCare Premium Support, 1 year', qty: 'All units' },
        ],
      },
      {
        system: 'CCTV',
        vendor: 'Hikvision',
        items: [
          { item: 'DS-2CD1743G2-LIZU 4MP dual-light varifocal dome', qty: '51' },
          { item: 'DS-2CD1643G2-LIZU 4MP dual-light varifocal bullet', qty: '12' },
          { item: 'Cat6 camera cabling, termination and testing', qty: '63 runs' },
        ],
      },
      {
        system: 'Access Control',
        vendor: 'Suprema',
        items: [
          { item: 'XPass XP2-MDPB dual-RFID mullion reader (IP67, IK08)', qty: '12' },
          { item: 'Magnetic lock, 600 lbs', qty: '13' },
          { item: 'No-touch exit button', qty: '12' },
          { item: 'Emergency break-glass unit', qty: '12' },
          { item: 'BioStar 2 Standard licence, 50 doors', qty: '1' },
        ],
      },
      {
        system: 'Power Protection',
        vendor: 'Eaton',
        items: [
          { item: '9SX 6000i RT3U online UPS', qty: '1' },
          { item: '5PX 1000VA RT2U UPS', qty: '1' },
        ],
      },
    ],
    // What the client received at handover — claims limited to what the BOQ evidences.
    handover: [
      {
        title: 'Certified test results',
        text: 'Every copper link Fluke channel-tested and every fiber core OTDR-tested, with reports issued as part of handover.',
      },
      {
        title: 'Labeled and documented',
        text: 'Racks, patch panels, outlets and fiber cores labeled to a consistent scheme so future changes start from a known state.',
      },
      {
        title: 'Manufacturer support registered',
        text: 'FortiCare Premium Support registered on all switches and access points, with the BioStar 2 licence issued in the client’s name.',
      },
      {
        title: 'One accountable contractor',
        text: 'Cabling, network, CCTV, access control and power delivered under a single scope — one team to call, not five.',
      },
    ],
  },
  {
    name: 'Mubadala Arena Abu Dhabi',
    slug: 'mubadala-arena-abu-dhabi',
    type: 'Enterprise Facilities',
    industry: 'Sports & Venues',
    location: 'Abu Dhabi, UAE',
    year: 'Delivered',
    services: [service.cabling, service.network],
    proofPoint: 'Venue infrastructure delivery supporting data, voice cabling and fiber connectivity.',
    challenge: 'Venue environments need reliable physical network foundations before tenant, visitor and operations systems can perform.',
    scope: 'Structured cabling and fiber-ready network infrastructure.',
    outcome: 'Handover-ready infrastructure for a high-value sports and venue environment.',
    featured: true,
    priority: 21,
    image: '/images/services/structured-cabling-what-we-cover.webp',
    imageAlt: 'Structured cabling and network infrastructure delivery by IP Care',
    imageVerified: false,
    imageCaption: 'Representative structured cabling delivery visual',
    relatedHref: '/services/elv/structured-cabling',
  },
  {
    name: 'GEMS American Academy',
    slug: 'gems-american-academy',
    type: 'Enterprise Facilities',
    industry: 'Education & Training',
    location: 'UAE',
    year: 'Delivered',
    services: [service.cabling, service.network],
    proofPoint: 'Education campus network infrastructure delivered through structured data and voice cabling.',
    challenge: 'Campus environments need clean cabling, predictable network rooms and room-to-room reliability.',
    scope: 'Data and voice cabling infrastructure.',
    outcome: 'Campus-ready connectivity for teaching, administration and operations.',
    featured: true,
    priority: 22,
    image: '/images/services/infrastructure-what-we-cover.webp',
    imageAlt: 'Campus network and infrastructure delivery by IP Care',
    imageVerified: false,
    imageCaption: 'Representative campus infrastructure delivery visual',
    relatedHref: '/services/infrastructure',
  },
  {
    name: 'Fairmont Bab Al Bahr, Abu Dhabi',
    slug: 'fairmont-bab-al-bahr-abu-dhabi',
    type: 'ELV & Security',
    industry: 'Hospitality',
    location: 'Abu Dhabi, UAE',
    year: 'Delivered',
    services: [service.cctv, service.elv],
    proofPoint: 'Premium hospitality CCTV deployment supporting physical security and operational visibility.',
    challenge: 'Hotel environments need discreet, reliable coverage without disrupting guest experience.',
    scope: 'CCTV systems for hospitality security and operations.',
    outcome: 'Security visibility delivered for a recognized hospitality property.',
    featured: true,
    priority: 23,
    image: '/images/services/cctv-what-we-cover.webp',
    imageAlt: 'CCTV systems delivery by IP Care for hospitality and commercial sites',
    imageVerified: false,
    imageCaption: 'Representative CCTV systems delivery visual',
    relatedHref: '/services/elv/cctv-systems',
  },
  {
    name: 'Crowne Plaza Hotel',
    slug: 'crowne-plaza-hotel',
    type: 'ELV & Security',
    industry: 'Hospitality',
    location: 'UAE',
    year: 'Delivered',
    services: [service.cctv, service.elv],
    proofPoint: 'Hotel security infrastructure delivered through CCTV systems deployment.',
    challenge: 'Hospitality security needs coverage that supports operations while staying unobtrusive for guests.',
    scope: 'CCTV systems deployment.',
    outcome: 'Operational visibility and site-security support for hotel teams.',
    featured: true,
    priority: 24,
    image: '/images/services/cctv-uae.webp',
    imageAlt: 'Hospitality CCTV systems installed by IP Care',
    imageVerified: false,
    imageCaption: 'Representative hospitality CCTV delivery visual',
    relatedHref: '/services/elv/cctv-systems',
  },
  {
    name: 'Paragone Mall',
    slug: 'paragone-mall',
    type: 'ELV & Security',
    industry: 'Retail & Commercial',
    location: 'UAE',
    year: 'Spelling QA Required',
    services: [service.cctv, service.cabling],
    proofPoint: 'Retail and commercial infrastructure delivery covering CCTV systems and data and voice cabling.',
    challenge: 'Retail environments need public-area security and back-of-house connectivity delivered around business operations.',
    scope: 'CCTV systems plus structured data and voice cabling.',
    outcome: 'Combined security and cabling scope under one delivery team.',
    featured: true,
    priority: 25,
    image: '/images/services/access-control-what-we-cover.webp',
    imageAlt: 'Commercial ELV and security infrastructure delivery by IP Care',
    imageVerified: false,
    imageCaption: 'Representative commercial ELV delivery visual',
    relatedHref: '/services/elv',
  },
  {
    name: 'Soho Tower Saadiyat',
    slug: 'soho-tower-saadiyat',
    type: 'ELV & Security',
    industry: 'Towers & Real Estate',
    location: 'Saadiyat Island, Abu Dhabi',
    year: 'Delivered',
    services: [service.cctv, service.cabling, service.access],
    proofPoint: 'Tower infrastructure scope combining CCTV, structured cabling, fiber and access control.',
    challenge: 'Multi-tenant towers need physical security and network backbone planned as one operating layer.',
    scope: 'CCTV systems, cabling, fiber and access control.',
    outcome: 'Integrated tower systems with one handover path.',
    featured: false,
    priority: 30,
    image: '/images/services/elv-abu-dhabi-what-we-cover.webp',
    imageAlt: 'Tower ELV and access control systems delivered by IP Care',
    imageVerified: false,
    imageCaption: 'Representative tower ELV delivery visual',
    relatedHref: '/services/elv/abu-dhabi',
  },
  {
    name: 'Al Jeel Tower',
    slug: 'al-jeel-tower',
    type: 'ELV & Security',
    industry: 'Towers & Real Estate',
    location: 'Abu Dhabi, UAE',
    year: 'Delivered',
    deliveredYear: '2020',
    services: [service.cctv, service.cabling, service.access, service.elv],
    proofPoint:
      'A full ELV and ICT installation package across a 168-apartment residential and retail tower — 432 cameras, 2,391 data outlets, 95 controlled doors and close to 2,500 fiber splices, delivered as specialist subcontractor to the main systems integrator.',
    metaDescription:
      'Al Jeel Tower, Abu Dhabi: 432 CCTV cameras, 2,391 Cat6A outlets, 95 access-controlled doors, 82 racks and 2,464 fiber splices installed and tested by IP Care.',
    challenge:
      'A live residential tower build with 168 apartments, retail units and GSM rooms — every flat, riser and equipment room needing cabling, fiber, cameras and door hardware installed to programme without holding up the main contractor.',
    scope:
      'In-apartment Cat6A and RG6 cabling, a single-mode fiber backbone from apartment ONUs through FTR to MTR, 432-camera CCTV, 95-door access control and 82 racks across every equipment room.',
    outcome:
      'Every link Fluke-tested, every fiber core spliced and tested, and every rack labeled to standard — an ELV package the main contractor could hand over without rework.',
    featured: false,
    priority: 31,
    // Real on-site photos from IP Care's Al Jeel Tower delivery.
    // The exterior is the only landscape, full-resolution asset, so it carries
    // the wide hero and the Open Graph card.
    image: '/images/portfolio/al-jeel-tower/tower-exterior.webp',
    imageAlt: 'Al Jeel Tower, Abu Dhabi — the residential and retail development IP Care delivered ELV and ICT systems for',
    imageVerified: true,
    imageCaption: 'Al Jeel Tower, Abu Dhabi',
    posterAspect: '16/10',
    posterSrcSet:
      '/images/portfolio/al-jeel-tower/tower-exterior-800.webp 800w, /images/portfolio/al-jeel-tower/tower-exterior.webp 1600w',
    relatedHref: '/services/elv',
    caseStudy: true,
    facts: [
      { label: 'Project', value: 'Al Jeel Tower' },
      { label: 'Sector', value: 'Residential & Retail Tower' },
      { label: 'Location', value: 'Abu Dhabi, UAE' },
      { label: 'Delivered', value: '2020' },
      { label: 'Role', value: 'ELV & ICT subcontractor to the main systems integrator' },
    ],
    stats: [
      { value: '432', label: 'CCTV cameras', note: '326 indoor, 106 outdoor' },
      { value: '2,391', label: 'Cat6A outlets', note: 'Dual point, Fluke tested' },
      { value: '2,464', label: 'Fiber splices', note: '2, 8 and 16-core single-mode' },
      { value: '95', label: 'Controlled doors', note: '67 single, 28 double' },
      { value: '82', label: 'Racks installed', note: '12U to 42U' },
      { value: '168', label: 'Apartments', note: 'Plus retail and GSM rooms' },
    ],
    workBreakdown: [
      {
        scope: 'CCTV Systems',
        icon: 'Cctv',
        blurb:
          'Four hundred and thirty-two cameras positioned, mounted and aligned across apartments levels, podium, parking and external approaches — each on a dedicated Cat6A run pulled, terminated and Fluke-tested before the camera went up.',
        specs: [
          '326 indoor cameras fixed and aligned',
          '106 outdoor cameras fixed and aligned',
          '432 dedicated Cat6A camera runs, terminated and Fluke-tested',
          '13 racks built out with CCTV equipment and terminations (10 × 27U, 3 × 42U)',
          '20 six-core fiber pulls from security IDF locations to the CCTV main rack',
        ],
        photos: [
          { src: '/images/portfolio/al-jeel-tower/cctv-install-ladder.webp', alt: 'IP Care technicians installing a soffit-mounted CCTV camera from a ladder at Al Jeel Tower, Abu Dhabi' },
          { src: '/images/portfolio/al-jeel-tower/cctv-install-corridor.webp', alt: 'IP Care technician mounting an internal CCTV camera in a corridor at Al Jeel Tower' },
        ],
      },
      {
        scope: 'In-Apartment Cabling',
        icon: 'Cable',
        blurb:
          'Every one of 168 apartments cabled from the ONU to the faceplate — dual-point Cat6A for data and RG6 for television, terminated at both ends, patched into the floor rack and Fluke-certified flat by flat.',
        specs: [
          '2,391 Cat6A dual-point outlets pulled, terminated and Fluke-tested',
          '536 RG6 television points from ONU to faceplate',
          'Patch panel installation and termination at every floor rack',
          '168 apartments plus retail units completed',
        ],
        photos: [
          { src: '/images/portfolio/al-jeel-tower/apartment-outlet.webp', alt: 'IP Care technician terminating a data outlet inside an apartment at Al Jeel Tower' },
          { src: '/images/portfolio/al-jeel-tower/apartment-termination.webp', alt: 'IP Care technician terminating faceplate cabling in a finished apartment at Al Jeel Tower' },
          { src: '/images/portfolio/al-jeel-tower/apartment-fitout.webp', alt: 'IP Care team working through apartment fit-out cabling at Al Jeel Tower' },
        ],
      },
      {
        scope: 'Fiber Backbone & Splicing',
        icon: 'Waypoints',
        blurb:
          'The tower runs on single-mode fiber from each apartment ONU up through the floor rooms to the main telecom room. Close to 2,500 cores were spliced and tested — 2-core to the flats, 8- and 16-core on the risers and GSM links.',
        specs: [
          '336 splices on 2-core apartment ONU to FTR links, 168 pulls',
          '768 splices on 16-core FTR distribution, 48 pulls to MTR',
          '768 splices on 16-core terminations inside the main telecom room',
          '192 splices on 8-core GSM connectivity, GSM room and MTR sides',
          '100 splices on 8-core retail ONU links to FTR and MTR',
          '300 splices on 6-core security and ELV equipment room links',
          'Patch panel and drawer installation included throughout',
        ],
        photos: [
          { src: '/images/portfolio/al-jeel-tower/fiber-splicing.webp', alt: 'IP Care engineer splicing single-mode fiber into a splice tray on site at Al Jeel Tower' },
          { src: '/images/portfolio/al-jeel-tower/fiber-terminations.webp', alt: 'Terminated single-mode fiber patch panel with green APC connectors installed by IP Care at Al Jeel Tower' },
        ],
      },
      {
        scope: 'Access Control',
        icon: 'Fingerprint',
        blurb:
          'Ninety-five doors cabled and commissioned end to end — door contact, magnetic lock, push button, break glass and card reader on every leaf — with 61 access control panels and their power supplies installed in the telephone rooms.',
        specs: [
          '67 single-door sets: door contact, maglock, push button, break glass, card reader',
          '28 double-door sets: 2 × door contact and maglock, plus push button, break glass, card reader',
          '61 access control panels and 61 power supplies installed in telephone rooms',
          '1 × 27U rack built out in the main ELV room with access control equipment',
          'Cable pulling, installation, termination and testing on every device',
        ],
        photos: [
          { src: '/images/portfolio/al-jeel-tower/panel-installation.webp', alt: 'IP Care technician installing and wiring an access control panel enclosure at Al Jeel Tower' },
          { src: '/images/portfolio/al-jeel-tower/panel-apartment.webp', alt: 'IP Care team commissioning a wall-mounted ELV panel at Al Jeel Tower' },
        ],
      },
      {
        scope: 'Racks & Equipment Rooms',
        icon: 'Server',
        blurb:
          'Eighty-two racks installed and dressed across floor telecom rooms, GSM rooms, retail units, the main telecom room and the ELV room — each one built out with its equipment, patched, labeled and left ready for handover.',
        specs: [
          '49 × 12U racks in floor telecom rooms (FTR)',
          '8 × 42U racks in the main telecom room',
          '6 × 12U GSM racks and 5 × 15U racks in retail units',
          '13 × CCTV racks (10 × 27U, 3 × 42U) and 1 × 27U ELV rack',
          'Equipment mounting, termination and labeling to standard throughout',
        ],
        photos: [
          { src: '/images/portfolio/al-jeel-tower/fiber-patch-panels.webp', alt: 'Rack of terminated fiber patch panels with single-mode patch cords installed by IP Care at Al Jeel Tower' },
          { src: '/images/portfolio/al-jeel-tower/riser-cabling.webp', alt: 'IP Care technicians pulling and dressing riser cabling at Al Jeel Tower' },
        ],
      },
    ],
    // Labour and installation package — the main contractor supplied the
    // equipment, so this schedule lists work performed rather than hardware.
    techStackEyebrow: 'Scope schedule',
    techStackTitle: 'The work, item by item',
    techStackIntro:
      'The installation scope delivered at Al Jeel Tower, discipline by discipline. Equipment was supplied by the main contractor; every quantity below is work carried out, terminated and tested by IP Care.',
    techStackItemLabel: 'Work item',
    techStackCaption: 'installation scope delivered',
    techStack: [
      {
        system: 'CCTV',
        items: [
          { item: 'Cat6A pulling, termination and Fluke testing for cameras', qty: '432' },
          { item: 'Indoor camera fixing', qty: '326' },
          { item: 'Outdoor camera fixing', qty: '106' },
          { item: '27U rack installation with CCTV equipment and termination', qty: '10' },
          { item: '42U rack installation with CCTV equipment and termination', qty: '3' },
          { item: '6-core fiber pulling, security IDF to CCTV main rack', qty: '20' },
          { item: '6-core fiber splicing and testing, incl. patch panel drawer', qty: '240' },
        ],
      },
      {
        system: 'Access Control',
        items: [
          { item: 'Single-door ACP set — cable, install, terminate, test', qty: '67' },
          { item: 'Double-door ACP set — cable, install, terminate, test', qty: '28' },
          { item: 'ACP panel installation in telephone rooms (incl. power supply)', qty: '61' },
          { item: '6-core fiber pulling, IDF rack to ELV equipment room', qty: '5' },
          { item: '6-core fiber splicing and testing, incl. patch panel drawer', qty: '60' },
          { item: '27U rack installation in main ELV room with ACS equipment', qty: '1' },
        ],
      },
      {
        system: 'In-Apartment Cabling',
        items: [
          { item: 'Cat6A dual-point pulling, termination and Fluke testing', qty: '2,391' },
          { item: 'RG6 TV cable pulling and termination, ONU to faceplate', qty: '536' },
        ],
      },
      {
        system: 'Fiber Backbone',
        items: [
          { item: '2-core pulling, apartment ONU to FTR (168 flats)', qty: '168' },
          { item: '2-core splicing and testing, apartment ONU to FTR', qty: '336' },
          { item: '16-core pulling, FTR to MTR', qty: '48' },
          { item: '16-core splicing and testing from FTR', qty: '768' },
          { item: '16-core splicing and testing inside MTR', qty: '768' },
          { item: '8-core pulling, GSM to MTR', qty: '12' },
          { item: '8-core splicing and testing, GSM room side', qty: '96' },
          { item: 'Splicing and testing for GSM connectivity, MTR side', qty: '96' },
          { item: '16-core pulling, retail ONU to FTR (8 cores terminated)', qty: '5' },
          { item: '8-core splicing and testing, retail ONU to FTR', qty: '50' },
          { item: '8-core splicing and testing, retail ONU FTR to MTR', qty: '50' },
        ],
      },
      {
        system: 'Racks',
        items: [
          { item: '12U rack installation in floor telecom rooms (FTR)', qty: '49' },
          { item: '42U rack installation', qty: '8' },
          { item: '12U rack installation (GSM rooms)', qty: '6' },
          { item: '15U rack installation in retail shops', qty: '5' },
        ],
      },
    ],
    handover: [
      {
        title: 'Fluke tested throughout',
        text: 'Every Cat6A link — 2,391 in the apartments and 432 on cameras — pulled, terminated and Fluke-tested as part of the installation scope.',
      },
      {
        title: 'Fiber spliced and tested',
        text: 'Close to 2,500 single-mode cores spliced and tested from apartment ONUs through floor rooms to the main telecom room, patch panels and drawers included.',
      },
      {
        title: 'Labeled to standard',
        text: 'Racks, panels, outlets and fiber cores labeled to the project standard, with all installation accessories and tooling supplied by IP Care.',
      },
      {
        title: 'Delivered to programme',
        text: 'Work staged with the main contractor across cabling, installation, termination, testing and final snagging so the ELV package never held up handover.',
      },
    ],
  },
  {
    name: 'Al Masaood Oil & Gas Company',
    slug: 'al-masaood-oil-gas-company',
    type: 'Enterprise Facilities',
    industry: 'Oil & Gas',
    location: 'Abu Dhabi, UAE',
    year: 'Delivered',
    services: [service.cctv, service.cabling],
    proofPoint: 'Industrial-sector security and cabling scope covering CCTV systems and data and voice infrastructure.',
    challenge: 'Energy-sector facilities need disciplined infrastructure, clear handover and strong operational visibility.',
    scope: 'CCTV systems plus structured cabling.',
    outcome: 'Industrial-site infrastructure delivered with enterprise operating discipline.',
    featured: false,
    priority: 32,
    image: '/images/services/security-assessment-what-we-cover.webp',
    imageAlt: 'Industrial security and infrastructure delivery by IP Care',
    imageVerified: false,
    imageCaption: 'Representative industrial infrastructure delivery visual',
    relatedHref: '/services/elv/cctv-systems',
  },
  {
    name: 'Royal International Construction',
    slug: 'royal-international-construction',
    type: 'Enterprise Facilities',
    industry: 'Construction',
    location: 'UAE',
    year: 'Delivered',
    services: [service.cabling, service.access],
    proofPoint: 'Construction-sector cabling and access control delivery for active project environments.',
    challenge: 'Contractor-led projects need site-ready systems that can be handed over cleanly to owners and consultants.',
    scope: 'Data and voice cabling plus access control.',
    outcome: 'Infrastructure delivery aligned to project handover expectations.',
    featured: false,
    priority: 33,
    image: '/images/services/gate-barriers-what-we-cover.webp',
    imageAlt: 'Access control and infrastructure delivery by IP Care for construction projects',
    imageVerified: false,
    imageCaption: 'Representative construction-site infrastructure visual',
    relatedHref: '/services/elv/access-control',
  },
  {
    name: 'Family Development Foundation',
    slug: 'family-development-foundation',
    type: 'Enterprise Facilities',
    industry: 'Government & Community',
    location: 'UAE',
    year: 'Delivered',
    services: [service.pa, service.elv],
    proofPoint: 'Community and public-service facility support through public address systems delivery.',
    challenge: 'Community facilities need clear, reliable communication systems that support staff and visitors.',
    scope: 'Public address systems.',
    outcome: 'Facility communication layer delivered by IP Care Technologies.',
    featured: false,
    priority: 34,
    image: '/images/services/public-address-what-we-cover.webp',
    imageAlt: 'Public address systems delivery by IP Care',
    imageVerified: false,
    imageCaption: 'Representative public address systems delivery visual',
    relatedHref: '/services/elv/public-address-systems',
  },
  {
    name: 'CMA CGM Shipping Agency SE LLC',
    slug: 'cma-cgm-shipping-agency-se-llc',
    type: 'Enterprise Facilities',
    industry: 'Logistics / Shipping',
    location: 'UAE',
    year: 'Delivered',
    services: [service.cabling, service.network],
    proofPoint: 'Logistics-sector data and voice cabling delivery for operational connectivity.',
    challenge: 'Shipping and logistics offices depend on clean connectivity for daily coordination and service operations.',
    scope: 'Data and voice cabling.',
    outcome: 'Reliable network foundation for business operations.',
    featured: false,
    priority: 35,
    image: '/images/services/network-management-what-we-cover.webp',
    imageAlt: 'Network infrastructure delivery by IP Care',
    imageVerified: false,
    imageCaption: 'Representative network infrastructure delivery visual',
    relatedHref: '/services/managed-it/network-management',
  },
  {
    name: 'Sands Hotel Abu Dhabi',
    slug: 'sands-hotel-abu-dhabi',
    type: 'ELV & Security',
    industry: 'Hospitality',
    location: 'Abu Dhabi, UAE',
    year: 'Delivered',
    services: [service.cctv, service.elv],
    proofPoint: 'Hospitality CCTV systems delivery supporting site security and operational visibility.',
    challenge: 'Hotel environments need dependable coverage for public, service and operational areas.',
    scope: 'CCTV systems deployment.',
    outcome: 'Security visibility delivered for hospitality operations.',
    featured: false,
    priority: 36,
    image: '/images/services/cctv-what-we-cover.webp',
    imageAlt: 'Hospitality CCTV systems delivery by IP Care',
    imageVerified: false,
    imageCaption: 'Representative hospitality CCTV delivery visual',
    relatedHref: '/services/elv/cctv-systems',
  },
  {
    name: 'SFC Plus Abu Dhabi, UAE',
    slug: 'sfc-plus-abu-dhabi-uae',
    type: 'ELV & Security',
    industry: 'F&B / Retail',
    location: 'Abu Dhabi, UAE',
    year: 'Delivered',
    services: [service.cctv, service.elv],
    proofPoint: 'Retail and food-service CCTV delivery for day-to-day operational visibility.',
    challenge: 'Customer-facing outlets need security coverage that supports staff, customers and incident review.',
    scope: 'CCTV systems deployment.',
    outcome: 'Practical security visibility for a live retail and F&B environment.',
    featured: false,
    priority: 37,
    image: '/images/services/cctv-uae.webp',
    imageAlt: 'Retail CCTV systems delivered by IP Care',
    imageVerified: false,
    imageCaption: 'Representative retail CCTV delivery visual',
    relatedHref: '/services/elv/cctv-systems',
  },
  {
    name: 'Emirates Driving School',
    slug: 'emirates-driving-school',
    type: 'Enterprise Facilities',
    industry: 'Education & Training',
    location: 'UAE',
    year: 'Delivered',
    services: [service.cabling, service.network],
    proofPoint: 'Training-facility cabling infrastructure delivered for data and voice connectivity.',
    challenge: 'Driving schools and training campuses need reliable room-to-room connectivity for operations and instruction.',
    scope: 'Data and voice cabling.',
    outcome: 'Campus connectivity foundation delivered for an active training environment.',
    featured: false,
    priority: 38,
    image: '/images/services/structured-cabling-uae.webp',
    imageAlt: 'Structured cabling delivery for training facilities by IP Care',
    imageVerified: false,
    imageCaption: 'Representative structured cabling delivery visual',
    relatedHref: '/services/elv/structured-cabling',
  },
  {
    name: 'Emirates Private School',
    slug: 'emirates-private-school',
    type: 'Enterprise Facilities',
    industry: 'Education & Training',
    location: 'UAE',
    year: 'Delivered',
    services: [service.cabling, service.network],
    proofPoint: 'School network infrastructure delivered through structured data and voice cabling.',
    challenge: 'Schools need reliable administrative, classroom and operations connectivity across campus spaces.',
    scope: 'Data and voice cabling.',
    outcome: 'Education campus network foundation delivered by IP Care Technologies.',
    featured: false,
    priority: 39,
    image: '/images/services/infrastructure-abu-dhabi.webp',
    imageAlt: 'Education campus network infrastructure delivery by IP Care',
    imageVerified: false,
    imageCaption: 'Representative education infrastructure delivery visual',
    relatedHref: '/services/infrastructure',
  },
  {
    name: 'Trianon Royal Hotel',
    slug: 'trianon-royal-hotel',
    type: 'ELV & Security',
    industry: 'Hospitality',
    location: 'UAE',
    year: 'Delivered',
    services: [service.cctv, service.elv],
    proofPoint: 'Hotel CCTV systems delivery supporting physical security and operational awareness.',
    challenge: 'Hospitality sites need reliable coverage across guest-facing and back-of-house areas.',
    scope: 'CCTV systems deployment.',
    outcome: 'Hospitality security layer delivered with clear operational value.',
    featured: false,
    priority: 40,
    image: '/images/services/cctv-what-we-cover.webp',
    imageAlt: 'Hotel CCTV systems delivery by IP Care',
    imageVerified: false,
    imageCaption: 'Representative hotel CCTV delivery visual',
    relatedHref: '/services/elv/cctv-systems',
  },
  {
    name: 'Abu Dhabi Masjid Project',
    slug: 'abu-dhabi-masjid-project',
    type: 'ELV & Security',
    industry: 'Government & Community',
    location: 'Abu Dhabi, UAE',
    year: 'Delivered',
    services: [service.cctv, service.elv],
    proofPoint: 'Community facility CCTV systems delivery supporting public-space visibility and security.',
    challenge: 'Community and worship facilities need security systems that are reliable, respectful and easy to operate.',
    scope: 'CCTV systems deployment.',
    outcome: 'Public-facing facility security support delivered by IP Care Technologies.',
    featured: false,
    priority: 41,
    image: '/images/services/elv-abu-dhabi.webp',
    imageAlt: 'Community facility ELV and CCTV delivery by IP Care',
    imageVerified: false,
    imageCaption: 'Representative community facility ELV delivery visual',
    relatedHref: '/services/elv/abu-dhabi',
  },
  {
    name: 'Al Bani Gen. Contracting & Gen. Maintenance LLC',
    slug: 'al-bani-general-contracting-maintenance-llc',
    type: 'Enterprise Facilities',
    industry: 'Construction',
    location: 'UAE',
    year: 'Delivered',
    services: [service.cabling, service.access],
    proofPoint: 'Contracting-sector infrastructure delivery covering data cabling and access control.',
    challenge: 'Construction and maintenance firms need practical systems that support active sites and office operations.',
    scope: 'Data and voice cabling plus access control.',
    outcome: 'Infrastructure and access scope delivered under one project path.',
    featured: false,
    priority: 42,
    image: '/images/services/access-control-what-we-cover.webp',
    imageAlt: 'Access control and cabling delivery by IP Care',
    imageVerified: false,
    imageCaption: 'Representative access control delivery visual',
    relatedHref: '/services/elv/access-control',
  },
  {
    name: 'ALBA-TEC Construction & Development LLC',
    slug: 'alba-tec-construction-development-llc',
    type: 'Enterprise Facilities',
    industry: 'Construction',
    location: 'UAE',
    year: 'Delivered',
    services: [service.cctv, service.cabling, service.access],
    proofPoint: 'Construction and development project scope covering CCTV, cabling and access control.',
    challenge: 'Developer-led sites need coordinated security, cabling and access systems rather than separate handoffs.',
    scope: 'CCTV systems, data and voice cabling and access control.',
    outcome: 'Multi-system project delivery through one accountable engineering team.',
    featured: false,
    priority: 43,
    image: '/images/services/elv-dubai-what-we-cover.webp',
    imageAlt: 'Construction ELV, CCTV and access control delivery by IP Care',
    imageVerified: false,
    imageCaption: 'Representative construction ELV delivery visual',
    relatedHref: '/services/elv',
  },
]

export const portfolioProjects = [...enterpriseProjects].sort((a, b) => a.priority - b.priority)

export const portfolioStats = [
  { value: '20+', label: 'Years in UAE' },
  { value: '500+', label: 'Projects delivered' },
  { value: '200+', label: 'Clients served' },
  { value: '24/7', label: 'Support capability' },
]

export const portfolioPillars = [
  {
    title: 'Enterprise Facilities',
    text: 'Hotels, schools, malls, arenas, towers and industrial sites supported by one engineering team.',
    proof: 'Hospitality, education, retail, venues, construction',
  },
  {
    title: 'ELV & Infrastructure',
    text: 'CCTV, access control, structured cabling, fiber and network infrastructure delivered as one stack.',
    proof: 'Security, cabling, access, network backbone',
  },
]

export const portfolioFilters = {
  types: ['All', 'Enterprise Facilities', 'ELV & Security'],
  industries: [
    'All',
    'Sports & Venues',
    'Hospitality',
    'Education & Training',
    'Retail & Commercial',
    'F&B / Retail',
    'Towers & Real Estate',
    'Oil & Gas',
    'Construction',
    'Government & Community',
    'Logistics / Shipping',
  ],
  services: [
    'All',
    'CCTV Systems',
    'CCTV & Access Control',
    'Access Control',
    'Structured Cabling & Fiber',
    'Network Infrastructure',
  ],
}

export const featuredPortfolioProjects = portfolioProjects.filter((project) => project.featured)

// Projects with a dedicated case-study detail page at /portfolio/[slug]
export const caseStudyProjects = portfolioProjects.filter((project) => project.caseStudy)
export const getCaseStudy = (slug) => portfolioProjects.find((project) => project.slug === slug && project.caseStudy) || null
export const getCaseStudySlugs = () => caseStudyProjects.map((project) => project.slug)
