const service = {
  cctv: { label: 'CCTV Systems', href: '/services/elv/cctv-systems' },
  access: { label: 'Access Control', href: '/services/elv/access-control' },
  cabling: { label: 'Structured Cabling & Fiber', href: '/services/elv/structured-cabling' },
  elv: { label: 'ELV & Physical Security', href: '/services/elv' },
  network: { label: 'Network Infrastructure', href: '/services/infrastructure' },
  managedIt: { label: 'Managed IT', href: '/services/managed-it' },
  pa: { label: 'PA Systems', href: '/services/elv/public-address-systems' },
}

const enterpriseProjects = [
  {
    name: 'Yas Driving Academy',
    slug: 'yas-driving-academy',
    type: 'Enterprise Facilities',
    industry: 'Education & Training',
    location: 'Abu Dhabi, UAE',
    year: 'Delivered',
    services: [service.cctv, service.cabling, service.access],
    proofPoint: 'Multi-system integration covering CCTV, structured cabling, fiber and access control for a critical training facility.',
    challenge: 'A high-use education and training environment needs security, connectivity and physical access working as one system.',
    scope: 'CCTV systems, data and voice cabling, fiber backbone and access control.',
    outcome: 'One accountable engineering team across security and infrastructure.',
    featured: true,
    priority: 20,
    image: '/images/portfolio/yas-driving-academy/hero.webp',
    imageAlt: 'IP Care delivery at Yas Driving Academy, Abu Dhabi — YDA facility and branded vehicle',
    imageVerified: true,
    imageCaption: 'IP Care on-site delivery at Yas Driving Academy',
    relatedHref: '/services/elv',
    // Real on-site project photos from IP Care's YDA delivery, grouped by scope of work.
    // See docs/superpowers/specs/2026-07-21-yas-driving-academy-video-case-study-design.md
    caseStudy: true,
    workBreakdown: [
      {
        scope: 'CCTV Systems',
        icon: 'Cctv',
        blurb:
          'Internal and external CCTV installed and aligned across the facility — cameras positioned for clear sightlines over entrances, circulation and operational areas.',
        photos: [
          { src: '/images/portfolio/yas-driving-academy/work-1.webp', alt: 'IP Care technician installing an external CCTV camera at Yas Driving Academy' },
        ],
      },
      {
        scope: 'Structured Cabling & Fiber',
        icon: 'Cable',
        blurb:
          'Structured data and voice cabling with a fibre backbone, routed through clean containment and floor boxes — a labelled foundation for every connected system.',
        photos: [
          { src: '/images/portfolio/yas-driving-academy/work-2.webp', alt: 'IP Care team installing overhead cabling and containment at Yas Driving Academy' },
          { src: '/images/portfolio/yas-driving-academy/work-3.webp', alt: 'IP Care technicians terminating floor data cabling at Yas Driving Academy' },
        ],
      },
      {
        scope: 'Access Control',
        icon: 'Fingerprint',
        blurb:
          'Access control readers and door hardware cabled and commissioned at controlled entry points, tied into the wider security stack.',
        photos: [
          { src: '/images/portfolio/yas-driving-academy/work-4.webp', alt: 'IP Care engineers routing cabling at an access-controlled entrance at Yas Driving Academy' },
        ],
      },
    ],
  },
  {
    name: 'Mubadala Arena Abu Dhabi',
    slug: 'mubadala-arena-abu-dhabi',
    type: 'Enterprise Facilities',
    industry: 'Sports & Venues',
    location: 'Abu Dhabi, UAE',
    year: 'Delivered',
    services: [service.cabling, service.network],
    proofPoint: 'Venue infrastructure delivery supporting data, voice cabling and fiber connectivity.',
    challenge: 'Venue environments need reliable physical network foundations before tenant, visitor and operations systems can perform.',
    scope: 'Structured cabling and fiber-ready network infrastructure.',
    outcome: 'Handover-ready infrastructure for a high-value sports and venue environment.',
    featured: true,
    priority: 21,
    image: '/images/services/structured-cabling-what-we-cover.webp',
    imageAlt: 'Structured cabling and network infrastructure delivery by IP Care',
    imageVerified: false,
    imageCaption: 'Representative structured cabling delivery visual',
    relatedHref: '/services/elv/structured-cabling',
  },
  {
    name: 'GEMS American Academy',
    slug: 'gems-american-academy',
    type: 'Enterprise Facilities',
    industry: 'Education & Training',
    location: 'UAE',
    year: 'Delivered',
    services: [service.cabling, service.network],
    proofPoint: 'Education campus network infrastructure delivered through structured data and voice cabling.',
    challenge: 'Campus environments need clean cabling, predictable network rooms and room-to-room reliability.',
    scope: 'Data and voice cabling infrastructure.',
    outcome: 'Campus-ready connectivity for teaching, administration and operations.',
    featured: true,
    priority: 22,
    image: '/images/services/infrastructure-what-we-cover.webp',
    imageAlt: 'Campus network and infrastructure delivery by IP Care',
    imageVerified: false,
    imageCaption: 'Representative campus infrastructure delivery visual',
    relatedHref: '/services/infrastructure',
  },
  {
    name: 'Fairmont Bab Al Bahr, Abu Dhabi',
    slug: 'fairmont-bab-al-bahr-abu-dhabi',
    type: 'ELV & Security',
    industry: 'Hospitality',
    location: 'Abu Dhabi, UAE',
    year: 'Delivered',
    services: [service.cctv, service.elv],
    proofPoint: 'Premium hospitality CCTV deployment supporting physical security and operational visibility.',
    challenge: 'Hotel environments need discreet, reliable coverage without disrupting guest experience.',
    scope: 'CCTV systems for hospitality security and operations.',
    outcome: 'Security visibility delivered for a recognized hospitality property.',
    featured: true,
    priority: 23,
    image: '/images/services/cctv-what-we-cover.webp',
    imageAlt: 'CCTV systems delivery by IP Care for hospitality and commercial sites',
    imageVerified: false,
    imageCaption: 'Representative CCTV systems delivery visual',
    relatedHref: '/services/elv/cctv-systems',
  },
  {
    name: 'Crowne Plaza Hotel',
    slug: 'crowne-plaza-hotel',
    type: 'ELV & Security',
    industry: 'Hospitality',
    location: 'UAE',
    year: 'Delivered',
    services: [service.cctv, service.elv],
    proofPoint: 'Hotel security infrastructure delivered through CCTV systems deployment.',
    challenge: 'Hospitality security needs coverage that supports operations while staying unobtrusive for guests.',
    scope: 'CCTV systems deployment.',
    outcome: 'Operational visibility and site-security support for hotel teams.',
    featured: true,
    priority: 24,
    image: '/images/services/cctv-uae.webp',
    imageAlt: 'Hospitality CCTV systems installed by IP Care',
    imageVerified: false,
    imageCaption: 'Representative hospitality CCTV delivery visual',
    relatedHref: '/services/elv/cctv-systems',
  },
  {
    name: 'Paragone Mall',
    slug: 'paragone-mall',
    type: 'ELV & Security',
    industry: 'Retail & Commercial',
    location: 'UAE',
    year: 'Spelling QA Required',
    services: [service.cctv, service.cabling],
    proofPoint: 'Retail and commercial infrastructure delivery covering CCTV systems and data and voice cabling.',
    challenge: 'Retail environments need public-area security and back-of-house connectivity delivered around business operations.',
    scope: 'CCTV systems plus structured data and voice cabling.',
    outcome: 'Combined security and cabling scope under one delivery team.',
    featured: true,
    priority: 25,
    image: '/images/services/access-control-what-we-cover.webp',
    imageAlt: 'Commercial ELV and security infrastructure delivery by IP Care',
    imageVerified: false,
    imageCaption: 'Representative commercial ELV delivery visual',
    relatedHref: '/services/elv',
  },
  {
    name: 'Soho Tower Saadiyat',
    slug: 'soho-tower-saadiyat',
    type: 'ELV & Security',
    industry: 'Towers & Real Estate',
    location: 'Saadiyat Island, Abu Dhabi',
    year: 'Delivered',
    services: [service.cctv, service.cabling, service.access],
    proofPoint: 'Tower infrastructure scope combining CCTV, structured cabling, fiber and access control.',
    challenge: 'Multi-tenant towers need physical security and network backbone planned as one operating layer.',
    scope: 'CCTV systems, cabling, fiber and access control.',
    outcome: 'Integrated tower systems with one handover path.',
    featured: false,
    priority: 30,
    image: '/images/services/elv-abu-dhabi-what-we-cover.webp',
    imageAlt: 'Tower ELV and access control systems delivered by IP Care',
    imageVerified: false,
    imageCaption: 'Representative tower ELV delivery visual',
    relatedHref: '/services/elv/abu-dhabi',
  },
  {
    name: 'Al Jeel Tower',
    slug: 'al-jeel-tower',
    type: 'ELV & Security',
    industry: 'Towers & Real Estate',
    location: 'UAE',
    year: 'Delivered',
    services: [service.cctv, service.cabling, service.access],
    proofPoint: 'Tower security and infrastructure delivery across CCTV, cabling, fiber and access control.',
    challenge: 'Building systems have to support residents, operations teams and facilities maintenance without vendor gaps.',
    scope: 'CCTV systems, data cabling, fiber and access control.',
    outcome: 'Integrated physical-security and network foundation.',
    featured: false,
    priority: 31,
    image: '/images/services/access-control-uae.webp',
    imageAlt: 'Access control and ELV systems delivered by IP Care',
    imageVerified: false,
    imageCaption: 'Representative access control delivery visual',
    relatedHref: '/services/elv/access-control',
  },
  {
    name: 'Al Masaood Oil & Gas Company',
    slug: 'al-masaood-oil-gas-company',
    type: 'Enterprise Facilities',
    industry: 'Oil & Gas',
    location: 'Abu Dhabi, UAE',
    year: 'Delivered',
    services: [service.cctv, service.cabling],
    proofPoint: 'Industrial-sector security and cabling scope covering CCTV systems and data and voice infrastructure.',
    challenge: 'Energy-sector facilities need disciplined infrastructure, clear handover and strong operational visibility.',
    scope: 'CCTV systems plus structured cabling.',
    outcome: 'Industrial-site infrastructure delivered with enterprise operating discipline.',
    featured: false,
    priority: 32,
    image: '/images/services/security-assessment-what-we-cover.webp',
    imageAlt: 'Industrial security and infrastructure delivery by IP Care',
    imageVerified: false,
    imageCaption: 'Representative industrial infrastructure delivery visual',
    relatedHref: '/services/elv/cctv-systems',
  },
  {
    name: 'Royal International Construction',
    slug: 'royal-international-construction',
    type: 'Enterprise Facilities',
    industry: 'Construction',
    location: 'UAE',
    year: 'Delivered',
    services: [service.cabling, service.access],
    proofPoint: 'Construction-sector cabling and access control delivery for active project environments.',
    challenge: 'Contractor-led projects need site-ready systems that can be handed over cleanly to owners and consultants.',
    scope: 'Data and voice cabling plus access control.',
    outcome: 'Infrastructure delivery aligned to project handover expectations.',
    featured: false,
    priority: 33,
    image: '/images/services/gate-barriers-what-we-cover.webp',
    imageAlt: 'Access control and infrastructure delivery by IP Care for construction projects',
    imageVerified: false,
    imageCaption: 'Representative construction-site infrastructure visual',
    relatedHref: '/services/elv/access-control',
  },
  {
    name: 'Family Development Foundation',
    slug: 'family-development-foundation',
    type: 'Enterprise Facilities',
    industry: 'Government & Community',
    location: 'UAE',
    year: 'Delivered',
    services: [service.pa, service.elv],
    proofPoint: 'Community and public-service facility support through public address systems delivery.',
    challenge: 'Community facilities need clear, reliable communication systems that support staff and visitors.',
    scope: 'Public address systems.',
    outcome: 'Facility communication layer delivered by IP Care Technologies.',
    featured: false,
    priority: 34,
    image: '/images/services/public-address-what-we-cover.webp',
    imageAlt: 'Public address systems delivery by IP Care',
    imageVerified: false,
    imageCaption: 'Representative public address systems delivery visual',
    relatedHref: '/services/elv/public-address-systems',
  },
  {
    name: 'CMA CGM Shipping Agency SE LLC',
    slug: 'cma-cgm-shipping-agency-se-llc',
    type: 'Enterprise Facilities',
    industry: 'Logistics / Shipping',
    location: 'UAE',
    year: 'Delivered',
    services: [service.cabling, service.network],
    proofPoint: 'Logistics-sector data and voice cabling delivery for operational connectivity.',
    challenge: 'Shipping and logistics offices depend on clean connectivity for daily coordination and service operations.',
    scope: 'Data and voice cabling.',
    outcome: 'Reliable network foundation for business operations.',
    featured: false,
    priority: 35,
    image: '/images/services/network-management-what-we-cover.webp',
    imageAlt: 'Network infrastructure delivery by IP Care',
    imageVerified: false,
    imageCaption: 'Representative network infrastructure delivery visual',
    relatedHref: '/services/managed-it/network-management',
  },
  {
    name: 'Sands Hotel Abu Dhabi',
    slug: 'sands-hotel-abu-dhabi',
    type: 'ELV & Security',
    industry: 'Hospitality',
    location: 'Abu Dhabi, UAE',
    year: 'Delivered',
    services: [service.cctv, service.elv],
    proofPoint: 'Hospitality CCTV systems delivery supporting site security and operational visibility.',
    challenge: 'Hotel environments need dependable coverage for public, service and operational areas.',
    scope: 'CCTV systems deployment.',
    outcome: 'Security visibility delivered for hospitality operations.',
    featured: false,
    priority: 36,
    image: '/images/services/cctv-what-we-cover.webp',
    imageAlt: 'Hospitality CCTV systems delivery by IP Care',
    imageVerified: false,
    imageCaption: 'Representative hospitality CCTV delivery visual',
    relatedHref: '/services/elv/cctv-systems',
  },
  {
    name: 'SFC Plus Abu Dhabi, UAE',
    slug: 'sfc-plus-abu-dhabi-uae',
    type: 'ELV & Security',
    industry: 'F&B / Retail',
    location: 'Abu Dhabi, UAE',
    year: 'Delivered',
    services: [service.cctv, service.elv],
    proofPoint: 'Retail and food-service CCTV delivery for day-to-day operational visibility.',
    challenge: 'Customer-facing outlets need security coverage that supports staff, customers and incident review.',
    scope: 'CCTV systems deployment.',
    outcome: 'Practical security visibility for a live retail and F&B environment.',
    featured: false,
    priority: 37,
    image: '/images/services/cctv-uae.webp',
    imageAlt: 'Retail CCTV systems delivered by IP Care',
    imageVerified: false,
    imageCaption: 'Representative retail CCTV delivery visual',
    relatedHref: '/services/elv/cctv-systems',
  },
  {
    name: 'Emirates Driving School',
    slug: 'emirates-driving-school',
    type: 'Enterprise Facilities',
    industry: 'Education & Training',
    location: 'UAE',
    year: 'Delivered',
    services: [service.cabling, service.network],
    proofPoint: 'Training-facility cabling infrastructure delivered for data and voice connectivity.',
    challenge: 'Driving schools and training campuses need reliable room-to-room connectivity for operations and instruction.',
    scope: 'Data and voice cabling.',
    outcome: 'Campus connectivity foundation delivered for an active training environment.',
    featured: false,
    priority: 38,
    image: '/images/services/structured-cabling-uae.webp',
    imageAlt: 'Structured cabling delivery for training facilities by IP Care',
    imageVerified: false,
    imageCaption: 'Representative structured cabling delivery visual',
    relatedHref: '/services/elv/structured-cabling',
  },
  {
    name: 'Emirates Private School',
    slug: 'emirates-private-school',
    type: 'Enterprise Facilities',
    industry: 'Education & Training',
    location: 'UAE',
    year: 'Delivered',
    services: [service.cabling, service.network],
    proofPoint: 'School network infrastructure delivered through structured data and voice cabling.',
    challenge: 'Schools need reliable administrative, classroom and operations connectivity across campus spaces.',
    scope: 'Data and voice cabling.',
    outcome: 'Education campus network foundation delivered by IP Care Technologies.',
    featured: false,
    priority: 39,
    image: '/images/services/infrastructure-abu-dhabi.webp',
    imageAlt: 'Education campus network infrastructure delivery by IP Care',
    imageVerified: false,
    imageCaption: 'Representative education infrastructure delivery visual',
    relatedHref: '/services/infrastructure',
  },
  {
    name: 'Trianon Royal Hotel',
    slug: 'trianon-royal-hotel',
    type: 'ELV & Security',
    industry: 'Hospitality',
    location: 'UAE',
    year: 'Delivered',
    services: [service.cctv, service.elv],
    proofPoint: 'Hotel CCTV systems delivery supporting physical security and operational awareness.',
    challenge: 'Hospitality sites need reliable coverage across guest-facing and back-of-house areas.',
    scope: 'CCTV systems deployment.',
    outcome: 'Hospitality security layer delivered with clear operational value.',
    featured: false,
    priority: 40,
    image: '/images/services/cctv-what-we-cover.webp',
    imageAlt: 'Hotel CCTV systems delivery by IP Care',
    imageVerified: false,
    imageCaption: 'Representative hotel CCTV delivery visual',
    relatedHref: '/services/elv/cctv-systems',
  },
  {
    name: 'Abu Dhabi Masjid Project',
    slug: 'abu-dhabi-masjid-project',
    type: 'ELV & Security',
    industry: 'Government & Community',
    location: 'Abu Dhabi, UAE',
    year: 'Delivered',
    services: [service.cctv, service.elv],
    proofPoint: 'Community facility CCTV systems delivery supporting public-space visibility and security.',
    challenge: 'Community and worship facilities need security systems that are reliable, respectful and easy to operate.',
    scope: 'CCTV systems deployment.',
    outcome: 'Public-facing facility security support delivered by IP Care Technologies.',
    featured: false,
    priority: 41,
    image: '/images/services/elv-abu-dhabi.webp',
    imageAlt: 'Community facility ELV and CCTV delivery by IP Care',
    imageVerified: false,
    imageCaption: 'Representative community facility ELV delivery visual',
    relatedHref: '/services/elv/abu-dhabi',
  },
  {
    name: 'Al Bani Gen. Contracting & Gen. Maintenance LLC',
    slug: 'al-bani-general-contracting-maintenance-llc',
    type: 'Enterprise Facilities',
    industry: 'Construction',
    location: 'UAE',
    year: 'Delivered',
    services: [service.cabling, service.access],
    proofPoint: 'Contracting-sector infrastructure delivery covering data cabling and access control.',
    challenge: 'Construction and maintenance firms need practical systems that support active sites and office operations.',
    scope: 'Data and voice cabling plus access control.',
    outcome: 'Infrastructure and access scope delivered under one project path.',
    featured: false,
    priority: 42,
    image: '/images/services/access-control-what-we-cover.webp',
    imageAlt: 'Access control and cabling delivery by IP Care',
    imageVerified: false,
    imageCaption: 'Representative access control delivery visual',
    relatedHref: '/services/elv/access-control',
  },
  {
    name: 'ALBA-TEC Construction & Development LLC',
    slug: 'alba-tec-construction-development-llc',
    type: 'Enterprise Facilities',
    industry: 'Construction',
    location: 'UAE',
    year: 'Delivered',
    services: [service.cctv, service.cabling, service.access],
    proofPoint: 'Construction and development project scope covering CCTV, cabling and access control.',
    challenge: 'Developer-led sites need coordinated security, cabling and access systems rather than separate handoffs.',
    scope: 'CCTV systems, data and voice cabling and access control.',
    outcome: 'Multi-system project delivery through one accountable engineering team.',
    featured: false,
    priority: 43,
    image: '/images/services/elv-dubai-what-we-cover.webp',
    imageAlt: 'Construction ELV, CCTV and access control delivery by IP Care',
    imageVerified: false,
    imageCaption: 'Representative construction ELV delivery visual',
    relatedHref: '/services/elv',
  },
]

export const portfolioProjects = [...enterpriseProjects].sort((a, b) => a.priority - b.priority)

export const portfolioStats = [
  { value: '20+', label: 'Years in UAE' },
  { value: '500+', label: 'Projects delivered' },
  { value: '200+', label: 'Clients served' },
  { value: '24/7', label: 'Support capability' },
]

export const portfolioPillars = [
  {
    title: 'Enterprise Facilities',
    text: 'Hotels, schools, malls, arenas, towers and industrial sites supported by one engineering team.',
    proof: 'Hospitality, education, retail, venues, construction',
  },
  {
    title: 'ELV & Infrastructure',
    text: 'CCTV, access control, structured cabling, fiber and network infrastructure delivered as one stack.',
    proof: 'Security, cabling, access, network backbone',
  },
]

export const portfolioFilters = {
  types: ['All', 'Enterprise Facilities', 'ELV & Security'],
  industries: [
    'All',
    'Sports & Venues',
    'Hospitality',
    'Education & Training',
    'Retail & Commercial',
    'F&B / Retail',
    'Towers & Real Estate',
    'Oil & Gas',
    'Construction',
    'Government & Community',
    'Logistics / Shipping',
  ],
  services: [
    'All',
    'CCTV Systems',
    'CCTV & Access Control',
    'Access Control',
    'Structured Cabling & Fiber',
    'Network Infrastructure',
  ],
}

export const featuredPortfolioProjects = portfolioProjects.filter((project) => project.featured)

// Projects with a dedicated case-study detail page at /portfolio/[slug]
export const caseStudyProjects = portfolioProjects.filter((project) => project.caseStudy)
export const getCaseStudy = (slug) => portfolioProjects.find((project) => project.slug === slug && project.caseStudy) || null
export const getCaseStudySlugs = () => caseStudyProjects.map((project) => project.slug)
